// Code generated by protoc-gen-go. DO NOT EDIT.
// source: portcullis.proto

/*
Package portcullis is a generated protocol buffer package.

It is generated from these files:
	portcullis.proto

It has these top-level messages:
	Scope
	CreateRoleRequest
	CompleteResponse
	RoleUsers
	Permission
	SetPermissionRequest
	GetPermissionRequest
	GetPermissionsResponse
*/
package portcullis

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PermissionType int32

const (
	PermissionType_NONE  PermissionType = 0
	PermissionType_ALLOW PermissionType = 1
	PermissionType_DENY  PermissionType = 2
	// Can be used on apps only, but will take permission from the requesting user
	PermissionType_INHERIT PermissionType = 3
)

var PermissionType_name = map[int32]string{
	0: "NONE",
	1: "ALLOW",
	2: "DENY",
	3: "INHERIT",
}
var PermissionType_value = map[string]int32{
	"NONE":    0,
	"ALLOW":   1,
	"DENY":    2,
	"INHERIT": 3,
}

func (x PermissionType) String() string {
	return proto.EnumName(PermissionType_name, int32(x))
}
func (PermissionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Scope struct {
	VendorId string `protobuf:"bytes,1,opt,name=vendor_id,json=vendorId" json:"vendor_id,omitempty"`
	AppId    string `protobuf:"bytes,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	Key      string `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Global   bool   `protobuf:"varint,4,opt,name=global" json:"global,omitempty"`
}

func (m *Scope) Reset()                    { *m = Scope{} }
func (m *Scope) String() string            { return proto.CompactTextString(m) }
func (*Scope) ProtoMessage()               {}
func (*Scope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Scope) GetVendorId() string {
	if m != nil {
		return m.VendorId
	}
	return ""
}

func (m *Scope) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Scope) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Scope) GetGlobal() bool {
	if m != nil {
		return m.Global
	}
	return false
}

type CreateRoleRequest struct {
	Id   *Scope `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
}

func (m *CreateRoleRequest) Reset()                    { *m = CreateRoleRequest{} }
func (m *CreateRoleRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRoleRequest) ProtoMessage()               {}
func (*CreateRoleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRoleRequest) GetId() *Scope {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CreateRoleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CompleteResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *CompleteResponse) Reset()                    { *m = CompleteResponse{} }
func (m *CompleteResponse) String() string            { return proto.CompactTextString(m) }
func (*CompleteResponse) ProtoMessage()               {}
func (*CompleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CompleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CompleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RoleUsers struct {
	Role    *Scope   `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	UserIds []string `protobuf:"bytes,2,rep,name=user_ids,json=userIds" json:"user_ids,omitempty"`
}

func (m *RoleUsers) Reset()                    { *m = RoleUsers{} }
func (m *RoleUsers) String() string            { return proto.CompactTextString(m) }
func (*RoleUsers) ProtoMessage()               {}
func (*RoleUsers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RoleUsers) GetRole() *Scope {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *RoleUsers) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type Permission struct {
	Id   *Scope         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type PermissionType `protobuf:"varint,2,opt,name=type,enum=portcullis.PermissionType" json:"type,omitempty"`
}

func (m *Permission) Reset()                    { *m = Permission{} }
func (m *Permission) String() string            { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()               {}
func (*Permission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Permission) GetId() *Scope {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Permission) GetType() PermissionType {
	if m != nil {
		return m.Type
	}
	return PermissionType_NONE
}

type SetPermissionRequest struct {
	ApplyToIds  []string      `protobuf:"bytes,1,rep,name=apply_to_ids,json=applyToIds" json:"apply_to_ids,omitempty"`
	Permissions []*Permission `protobuf:"bytes,2,rep,name=permissions" json:"permissions,omitempty"`
}

func (m *SetPermissionRequest) Reset()                    { *m = SetPermissionRequest{} }
func (m *SetPermissionRequest) String() string            { return proto.CompactTextString(m) }
func (*SetPermissionRequest) ProtoMessage()               {}
func (*SetPermissionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SetPermissionRequest) GetApplyToIds() []string {
	if m != nil {
		return m.ApplyToIds
	}
	return nil
}

func (m *SetPermissionRequest) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type GetPermissionRequest struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	VendorId string `protobuf:"bytes,2,opt,name=vendor_id,json=vendorId" json:"vendor_id,omitempty"`
	AppId    string `protobuf:"bytes,3,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	// Include prefixes to search for e.g. projectID/ projectID/Kubex projectID/kubex/teams
	Prefixes           []string `protobuf:"bytes,4,rep,name=prefixes" json:"prefixes,omitempty"`
	IncludeRoles       bool     `protobuf:"varint,5,opt,name=include_roles,json=includeRoles" json:"include_roles,omitempty"`
	IncludePermissions bool     `protobuf:"varint,6,opt,name=include_permissions,json=includePermissions" json:"include_permissions,omitempty"`
}

func (m *GetPermissionRequest) Reset()                    { *m = GetPermissionRequest{} }
func (m *GetPermissionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPermissionRequest) ProtoMessage()               {}
func (*GetPermissionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetPermissionRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetPermissionRequest) GetVendorId() string {
	if m != nil {
		return m.VendorId
	}
	return ""
}

func (m *GetPermissionRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GetPermissionRequest) GetPrefixes() []string {
	if m != nil {
		return m.Prefixes
	}
	return nil
}

func (m *GetPermissionRequest) GetIncludeRoles() bool {
	if m != nil {
		return m.IncludeRoles
	}
	return false
}

func (m *GetPermissionRequest) GetIncludePermissions() bool {
	if m != nil {
		return m.IncludePermissions
	}
	return false
}

type GetPermissionsResponse struct {
	Roles       []string      `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
	Permissions []*Permission `protobuf:"bytes,2,rep,name=permissions" json:"permissions,omitempty"`
}

func (m *GetPermissionsResponse) Reset()                    { *m = GetPermissionsResponse{} }
func (m *GetPermissionsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPermissionsResponse) ProtoMessage()               {}
func (*GetPermissionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetPermissionsResponse) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *GetPermissionsResponse) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func init() {
	proto.RegisterType((*Scope)(nil), "portcullis.Scope")
	proto.RegisterType((*CreateRoleRequest)(nil), "portcullis.CreateRoleRequest")
	proto.RegisterType((*CompleteResponse)(nil), "portcullis.CompleteResponse")
	proto.RegisterType((*RoleUsers)(nil), "portcullis.RoleUsers")
	proto.RegisterType((*Permission)(nil), "portcullis.Permission")
	proto.RegisterType((*SetPermissionRequest)(nil), "portcullis.SetPermissionRequest")
	proto.RegisterType((*GetPermissionRequest)(nil), "portcullis.GetPermissionRequest")
	proto.RegisterType((*GetPermissionsResponse)(nil), "portcullis.GetPermissionsResponse")
	proto.RegisterEnum("portcullis.PermissionType", PermissionType_name, PermissionType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Portcullis service

type PortcullisClient interface {
	CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CompleteResponse, error)
	AddToRole(ctx context.Context, in *RoleUsers, opts ...grpc.CallOption) (*CompleteResponse, error)
	QueryRole(ctx context.Context, in *Scope, opts ...grpc.CallOption) (*RoleUsers, error)
	RemoveFromRole(ctx context.Context, in *RoleUsers, opts ...grpc.CallOption) (*CompleteResponse, error)
	SetPermissions(ctx context.Context, in *SetPermissionRequest, opts ...grpc.CallOption) (*CompleteResponse, error)
	GetPermissions(ctx context.Context, in *GetPermissionRequest, opts ...grpc.CallOption) (*GetPermissionsResponse, error)
}

type portcullisClient struct {
	cc *grpc.ClientConn
}

func NewPortcullisClient(cc *grpc.ClientConn) PortcullisClient {
	return &portcullisClient{cc}
}

func (c *portcullisClient) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CompleteResponse, error) {
	out := new(CompleteResponse)
	err := grpc.Invoke(ctx, "/portcullis.Portcullis/CreateRole", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portcullisClient) AddToRole(ctx context.Context, in *RoleUsers, opts ...grpc.CallOption) (*CompleteResponse, error) {
	out := new(CompleteResponse)
	err := grpc.Invoke(ctx, "/portcullis.Portcullis/AddToRole", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portcullisClient) QueryRole(ctx context.Context, in *Scope, opts ...grpc.CallOption) (*RoleUsers, error) {
	out := new(RoleUsers)
	err := grpc.Invoke(ctx, "/portcullis.Portcullis/QueryRole", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portcullisClient) RemoveFromRole(ctx context.Context, in *RoleUsers, opts ...grpc.CallOption) (*CompleteResponse, error) {
	out := new(CompleteResponse)
	err := grpc.Invoke(ctx, "/portcullis.Portcullis/RemoveFromRole", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portcullisClient) SetPermissions(ctx context.Context, in *SetPermissionRequest, opts ...grpc.CallOption) (*CompleteResponse, error) {
	out := new(CompleteResponse)
	err := grpc.Invoke(ctx, "/portcullis.Portcullis/SetPermissions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portcullisClient) GetPermissions(ctx context.Context, in *GetPermissionRequest, opts ...grpc.CallOption) (*GetPermissionsResponse, error) {
	out := new(GetPermissionsResponse)
	err := grpc.Invoke(ctx, "/portcullis.Portcullis/GetPermissions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Portcullis service

type PortcullisServer interface {
	CreateRole(context.Context, *CreateRoleRequest) (*CompleteResponse, error)
	AddToRole(context.Context, *RoleUsers) (*CompleteResponse, error)
	QueryRole(context.Context, *Scope) (*RoleUsers, error)
	RemoveFromRole(context.Context, *RoleUsers) (*CompleteResponse, error)
	SetPermissions(context.Context, *SetPermissionRequest) (*CompleteResponse, error)
	GetPermissions(context.Context, *GetPermissionRequest) (*GetPermissionsResponse, error)
}

func RegisterPortcullisServer(s *grpc.Server, srv PortcullisServer) {
	s.RegisterService(&_Portcullis_serviceDesc, srv)
}

func _Portcullis_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortcullisServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portcullis.Portcullis/CreateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortcullisServer).CreateRole(ctx, req.(*CreateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portcullis_AddToRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleUsers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortcullisServer).AddToRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portcullis.Portcullis/AddToRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortcullisServer).AddToRole(ctx, req.(*RoleUsers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portcullis_QueryRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Scope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortcullisServer).QueryRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portcullis.Portcullis/QueryRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortcullisServer).QueryRole(ctx, req.(*Scope))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portcullis_RemoveFromRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleUsers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortcullisServer).RemoveFromRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portcullis.Portcullis/RemoveFromRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortcullisServer).RemoveFromRole(ctx, req.(*RoleUsers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portcullis_SetPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortcullisServer).SetPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portcullis.Portcullis/SetPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortcullisServer).SetPermissions(ctx, req.(*SetPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Portcullis_GetPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortcullisServer).GetPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portcullis.Portcullis/GetPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortcullisServer).GetPermissions(ctx, req.(*GetPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Portcullis_serviceDesc = grpc.ServiceDesc{
	ServiceName: "portcullis.Portcullis",
	HandlerType: (*PortcullisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRole",
			Handler:    _Portcullis_CreateRole_Handler,
		},
		{
			MethodName: "AddToRole",
			Handler:    _Portcullis_AddToRole_Handler,
		},
		{
			MethodName: "QueryRole",
			Handler:    _Portcullis_QueryRole_Handler,
		},
		{
			MethodName: "RemoveFromRole",
			Handler:    _Portcullis_RemoveFromRole_Handler,
		},
		{
			MethodName: "SetPermissions",
			Handler:    _Portcullis_SetPermissions_Handler,
		},
		{
			MethodName: "GetPermissions",
			Handler:    _Portcullis_GetPermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portcullis.proto",
}

func init() { proto.RegisterFile("portcullis.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 617 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xfd, 0xf2, 0x6f, 0x4f, 0xfa, 0x45, 0xee, 0x92, 0x16, 0x13, 0x40, 0x0a, 0xe6, 0x47, 0x15,
	0x12, 0x89, 0x14, 0x84, 0xc4, 0x05, 0x17, 0xb4, 0x25, 0x14, 0xa3, 0x92, 0x86, 0x6d, 0x00, 0xc1,
	0x4d, 0x94, 0xc4, 0x43, 0x6b, 0xd5, 0xce, 0x2e, 0xbb, 0x76, 0xd5, 0x3c, 0x1e, 0x0f, 0xc1, 0xfb,
	0x20, 0xaf, 0x1d, 0xc7, 0xa6, 0x29, 0x45, 0xbd, 0xf3, 0xfc, 0xec, 0x39, 0x67, 0x67, 0xcf, 0x18,
	0x0c, 0xce, 0x44, 0x30, 0x0b, 0x3d, 0xcf, 0x95, 0x1d, 0x2e, 0x58, 0xc0, 0x08, 0xac, 0x32, 0x16,
	0x42, 0xe5, 0x78, 0xc6, 0x38, 0x92, 0xbb, 0xa0, 0x9f, 0xe3, 0xdc, 0x61, 0x62, 0xec, 0x3a, 0x66,
	0xa1, 0x5d, 0xd8, 0xd1, 0xa9, 0x16, 0x27, 0x6c, 0x87, 0x6c, 0x41, 0x75, 0xc2, 0x79, 0x54, 0x29,
	0xaa, 0x4a, 0x65, 0xc2, 0xb9, 0xed, 0x10, 0x03, 0x4a, 0x67, 0xb8, 0x30, 0x4b, 0x2a, 0x17, 0x7d,
	0x92, 0x6d, 0xa8, 0x9e, 0x78, 0x6c, 0x3a, 0xf1, 0xcc, 0x72, 0xbb, 0xb0, 0xa3, 0xd1, 0x24, 0xb2,
	0xde, 0xc3, 0xe6, 0xbe, 0xc0, 0x49, 0x80, 0x94, 0x79, 0x48, 0xf1, 0x47, 0x88, 0x32, 0x20, 0x0f,
	0xa0, 0x98, 0x70, 0xd5, 0x7b, 0x9b, 0x9d, 0x8c, 0x4c, 0xa5, 0x88, 0x16, 0x5d, 0x87, 0x10, 0x28,
	0xcf, 0x27, 0x3e, 0x9a, 0x15, 0x45, 0xa1, 0xbe, 0xad, 0x3d, 0x30, 0xf6, 0x99, 0xcf, 0x3d, 0x0c,
	0x90, 0xa2, 0xe4, 0x6c, 0x2e, 0x91, 0x98, 0x50, 0x93, 0xe1, 0x6c, 0x86, 0x52, 0x2a, 0x3c, 0x8d,
	0x2e, 0x43, 0xd2, 0x84, 0x0a, 0x0a, 0xc1, 0xc4, 0x52, 0xb9, 0x0a, 0xac, 0x0f, 0xa0, 0x47, 0x4a,
	0x3e, 0x49, 0x14, 0x92, 0x3c, 0x86, 0xb2, 0x60, 0x1e, 0x5e, 0xad, 0x44, 0x95, 0xc9, 0x1d, 0xd0,
	0x42, 0x89, 0xd1, 0x7c, 0xa4, 0x59, 0x6c, 0x97, 0x76, 0x74, 0x5a, 0x8b, 0x62, 0xdb, 0x91, 0xd6,
	0x18, 0x60, 0x88, 0xc2, 0x77, 0xa5, 0x74, 0xd9, 0xfc, 0x5f, 0xee, 0xd5, 0x81, 0x72, 0xb0, 0xe0,
	0xa8, 0x44, 0x35, 0x7a, 0xad, 0x6c, 0xd3, 0x0a, 0x68, 0xb4, 0x88, 0xb8, 0xa3, 0x3e, 0x4b, 0x40,
	0xf3, 0x18, 0x83, 0x55, 0x69, 0x39, 0xc2, 0x36, 0x6c, 0x4c, 0x38, 0xf7, 0x16, 0xe3, 0x80, 0x29,
	0x5d, 0x05, 0xa5, 0x0b, 0x54, 0x6e, 0xc4, 0x6c, 0x47, 0x92, 0x97, 0x50, 0xe7, 0xe9, 0xb1, 0x58,
	0x78, 0xbd, 0xb7, 0xbd, 0x9e, 0x90, 0x66, 0x5b, 0xad, 0x5f, 0x05, 0x68, 0x1e, 0xac, 0x23, 0xbd,
	0x0d, 0xb5, 0x64, 0x10, 0x89, 0x51, 0xaa, 0xf1, 0x1c, 0xf2, 0x1e, 0x2a, 0x5e, 0xe9, 0xa1, 0x52,
	0xd6, 0x43, 0x2d, 0xd0, 0xb8, 0xc0, 0xef, 0xee, 0x05, 0x4a, 0xb3, 0xac, 0xd4, 0xa7, 0x31, 0x79,
	0x08, 0xff, 0xbb, 0xf3, 0x99, 0x17, 0x3a, 0x38, 0x8e, 0x5e, 0x40, 0x2a, 0x1b, 0x68, 0x74, 0x23,
	0x49, 0x46, 0x2f, 0x28, 0x49, 0x17, 0x6e, 0x2d, 0x9b, 0xb2, 0x17, 0xad, 0xaa, 0x56, 0x92, 0x94,
	0x86, 0x99, 0x7b, 0x9d, 0xc2, 0x76, 0xee, 0x5a, 0x32, 0x75, 0x51, 0x13, 0x2a, 0x31, 0x4f, 0x3c,
	0xc6, 0x38, 0xb8, 0xf9, 0x04, 0x9f, 0xbe, 0x82, 0x46, 0xfe, 0x35, 0x89, 0x06, 0xe5, 0xc1, 0xd1,
	0xa0, 0x6f, 0xfc, 0x47, 0x74, 0xa8, 0xec, 0x1e, 0x1e, 0x1e, 0x7d, 0x31, 0x0a, 0x51, 0xf2, 0x4d,
	0x7f, 0xf0, 0xd5, 0x28, 0x92, 0x3a, 0xd4, 0xec, 0xc1, 0xbb, 0x3e, 0xb5, 0x47, 0x46, 0xa9, 0xf7,
	0xb3, 0x04, 0x30, 0x4c, 0x49, 0x88, 0x0d, 0xb0, 0x5a, 0x21, 0x72, 0x3f, 0xcb, 0x7f, 0x69, 0xb5,
	0x5a, 0xf7, 0x72, 0xe5, 0x3f, 0xb7, 0xe5, 0x35, 0xe8, 0xbb, 0x8e, 0x33, 0x62, 0x0a, 0x69, 0x2b,
	0xdb, 0x9a, 0x2e, 0xc5, 0x35, 0x08, 0x2f, 0x40, 0xff, 0x18, 0xa2, 0x58, 0x28, 0x84, 0xcb, 0x1e,
	0x6f, 0xad, 0x07, 0x25, 0x7d, 0x68, 0x50, 0xf4, 0xd9, 0x39, 0xbe, 0x15, 0xcc, 0xbf, 0x39, 0xfb,
	0x10, 0x1a, 0xb9, 0x6d, 0x90, 0xa4, 0x9d, 0x93, 0xb0, 0xc6, 0xb4, 0xd7, 0x20, 0x7e, 0x86, 0xc6,
	0xc1, 0x5f, 0x10, 0xd7, 0xad, 0x41, 0xcb, 0xba, 0xb2, 0x23, 0x75, 0xd4, 0xde, 0x93, 0x6f, 0x8f,
	0x4e, 0xdc, 0xe0, 0x34, 0x9c, 0x76, 0x66, 0xcc, 0xef, 0x9e, 0x85, 0x53, 0xbc, 0xe8, 0xaa, 0x9f,
	0xf0, 0xb3, 0x13, 0xd6, 0x5d, 0x1d, 0x9f, 0x56, 0x55, 0xf2, 0xf9, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x9d, 0x39, 0x84, 0x43, 0xad, 0x05, 0x00, 0x00,
}
