// Code generated by protoc-gen-go. DO NOT EDIT.
// source: project.proto

/*
Package project is a generated protocol buffer package.

It is generated from these files:
	project.proto

It has these top-level messages:
	CreateRequest
	RetrieveRequest
	ProjectResponse
	AddMemberRequest
	RemoveMemberRequest
	InviteRequest
	InviteStatusResponse
	ActionInviteRequest
	MemberStatusResponse
	GetMembersRequest
	GetProjectsRequest
	GetInvitesRequest
	InvitesResponse
	InviteResponse
	MembersResponse
	ProjectsResponse
	ProjectExistsResponse
	TimezoneRequest
	TimezoneResponse
*/
package project

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Mode int32

const (
	Mode_SANDBOX    Mode = 0
	Mode_PRODUCTION Mode = 1
	Mode_RESERVED   Mode = 2
)

var Mode_name = map[int32]string{
	0: "SANDBOX",
	1: "PRODUCTION",
	2: "RESERVED",
}
var Mode_value = map[string]int32{
	"SANDBOX":    0,
	"PRODUCTION": 1,
	"RESERVED":   2,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}
func (Mode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Region int32

const (
	Region_GLOBAL Region = 0
	Region_US     Region = 1
	Region_EUROPE Region = 2
	Region_ASIA   Region = 3
)

var Region_name = map[int32]string{
	0: "GLOBAL",
	1: "US",
	2: "EUROPE",
	3: "ASIA",
}
var Region_value = map[string]int32{
	"GLOBAL": 0,
	"US":     1,
	"EUROPE": 2,
	"ASIA":   3,
}

func (x Region) String() string {
	return proto.EnumName(Region_name, int32(x))
}
func (Region) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MemberType int32

const (
	MemberType_OWNER   MemberType = 0
	MemberType_MEMBER  MemberType = 1
	MemberType_VIEWER  MemberType = 2
	MemberType_SUPPORT MemberType = 3
)

var MemberType_name = map[int32]string{
	0: "OWNER",
	1: "MEMBER",
	2: "VIEWER",
	3: "SUPPORT",
}
var MemberType_value = map[string]int32{
	"OWNER":   0,
	"MEMBER":  1,
	"VIEWER":  2,
	"SUPPORT": 3,
}

func (x MemberType) String() string {
	return proto.EnumName(MemberType_name, int32(x))
}
func (MemberType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type InviteStatus int32

const (
	InviteStatus_PENDING   InviteStatus = 0
	InviteStatus_ACCEPTED  InviteStatus = 1
	InviteStatus_REJECTED  InviteStatus = 2
	InviteStatus_EXPIRED   InviteStatus = 3
	InviteStatus_NOT_FOUND InviteStatus = 4
)

var InviteStatus_name = map[int32]string{
	0: "PENDING",
	1: "ACCEPTED",
	2: "REJECTED",
	3: "EXPIRED",
	4: "NOT_FOUND",
}
var InviteStatus_value = map[string]int32{
	"PENDING":   0,
	"ACCEPTED":  1,
	"REJECTED":  2,
	"EXPIRED":   3,
	"NOT_FOUND": 4,
}

func (x InviteStatus) String() string {
	return proto.EnumName(InviteStatus_name, int32(x))
}
func (InviteStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type CreateRequest struct {
	Alias         string            `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	DistributorId string            `protobuf:"bytes,2,opt,name=distributor_id,json=distributorId" json:"distributor_id,omitempty"`
	Name          string            `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Mode          Mode              `protobuf:"varint,4,opt,name=mode,enum=project.Mode" json:"mode,omitempty"`
	Region        Region            `protobuf:"varint,5,opt,name=region,enum=project.Region" json:"region,omitempty"`
	Meta          map[string]string `protobuf:"bytes,6,rep,name=meta" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timezone      string            `protobuf:"bytes,7,opt,name=timezone" json:"timezone,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *CreateRequest) GetDistributorId() string {
	if m != nil {
		return m.DistributorId
	}
	return ""
}

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_SANDBOX
}

func (m *CreateRequest) GetRegion() Region {
	if m != nil {
		return m.Region
	}
	return Region_GLOBAL
}

func (m *CreateRequest) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *CreateRequest) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

type RetrieveRequest struct {
	Id            string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	DistributorId string `protobuf:"bytes,2,opt,name=distributor_id,json=distributorId" json:"distributor_id,omitempty"`
	Alias         string `protobuf:"bytes,3,opt,name=alias" json:"alias,omitempty"`
}

func (m *RetrieveRequest) Reset()                    { *m = RetrieveRequest{} }
func (m *RetrieveRequest) String() string            { return proto.CompactTextString(m) }
func (*RetrieveRequest) ProtoMessage()               {}
func (*RetrieveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RetrieveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RetrieveRequest) GetDistributorId() string {
	if m != nil {
		return m.DistributorId
	}
	return ""
}

func (m *RetrieveRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type ProjectResponse struct {
	Id             string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	DistributorId  string                     `protobuf:"bytes,2,opt,name=distributor_id,json=distributorId" json:"distributor_id,omitempty"`
	Alias          string                     `protobuf:"bytes,3,opt,name=alias" json:"alias,omitempty"`
	Name           string                     `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Mode           Mode                       `protobuf:"varint,5,opt,name=mode,enum=project.Mode" json:"mode,omitempty"`
	Region         Region                     `protobuf:"varint,6,opt,name=region,enum=project.Region" json:"region,omitempty"`
	Created        *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=created" json:"created,omitempty"`
	Timezone       string                     `protobuf:"bytes,8,opt,name=timezone" json:"timezone,omitempty"`
	TimezoneOffset int32                      `protobuf:"varint,9,opt,name=timezone_offset,json=timezoneOffset" json:"timezone_offset,omitempty"`
}

func (m *ProjectResponse) Reset()                    { *m = ProjectResponse{} }
func (m *ProjectResponse) String() string            { return proto.CompactTextString(m) }
func (*ProjectResponse) ProtoMessage()               {}
func (*ProjectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProjectResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProjectResponse) GetDistributorId() string {
	if m != nil {
		return m.DistributorId
	}
	return ""
}

func (m *ProjectResponse) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *ProjectResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProjectResponse) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_SANDBOX
}

func (m *ProjectResponse) GetRegion() Region {
	if m != nil {
		return m.Region
	}
	return Region_GLOBAL
}

func (m *ProjectResponse) GetCreated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *ProjectResponse) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *ProjectResponse) GetTimezoneOffset() int32 {
	if m != nil {
		return m.TimezoneOffset
	}
	return 0
}

type AddMemberRequest struct {
	MemberId      string                     `protobuf:"bytes,1,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	ProjectId     string                     `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	DistributorId string                     `protobuf:"bytes,3,opt,name=distributor_id,json=distributorId" json:"distributor_id,omitempty"`
	Type          MemberType                 `protobuf:"varint,4,opt,name=type,enum=project.MemberType" json:"type,omitempty"`
	Expiry        *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=expiry" json:"expiry,omitempty"`
}

func (m *AddMemberRequest) Reset()                    { *m = AddMemberRequest{} }
func (m *AddMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*AddMemberRequest) ProtoMessage()               {}
func (*AddMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddMemberRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *AddMemberRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *AddMemberRequest) GetDistributorId() string {
	if m != nil {
		return m.DistributorId
	}
	return ""
}

func (m *AddMemberRequest) GetType() MemberType {
	if m != nil {
		return m.Type
	}
	return MemberType_OWNER
}

func (m *AddMemberRequest) GetExpiry() *google_protobuf.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

type RemoveMemberRequest struct {
	MemberId      string `protobuf:"bytes,1,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	ProjectId     string `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	DistributorId string `protobuf:"bytes,3,opt,name=distributor_id,json=distributorId" json:"distributor_id,omitempty"`
}

func (m *RemoveMemberRequest) Reset()                    { *m = RemoveMemberRequest{} }
func (m *RemoveMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveMemberRequest) ProtoMessage()               {}
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RemoveMemberRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *RemoveMemberRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *RemoveMemberRequest) GetDistributorId() string {
	if m != nil {
		return m.DistributorId
	}
	return ""
}

type InviteRequest struct {
	Email         string                     `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	ProjectId     string                     `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	DistributorId string                     `protobuf:"bytes,3,opt,name=distributor_id,json=distributorId" json:"distributor_id,omitempty"`
	Type          MemberType                 `protobuf:"varint,4,opt,name=type,enum=project.MemberType" json:"type,omitempty"`
	Expiry        *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=expiry" json:"expiry,omitempty"`
}

func (m *InviteRequest) Reset()                    { *m = InviteRequest{} }
func (m *InviteRequest) String() string            { return proto.CompactTextString(m) }
func (*InviteRequest) ProtoMessage()               {}
func (*InviteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *InviteRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *InviteRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *InviteRequest) GetDistributorId() string {
	if m != nil {
		return m.DistributorId
	}
	return ""
}

func (m *InviteRequest) GetType() MemberType {
	if m != nil {
		return m.Type
	}
	return MemberType_OWNER
}

func (m *InviteRequest) GetExpiry() *google_protobuf.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

type InviteStatusResponse struct {
	Email        string                     `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Status       InviteStatus               `protobuf:"varint,2,opt,name=status,enum=project.InviteStatus" json:"status,omitempty"`
	Verification string                     `protobuf:"bytes,3,opt,name=verification" json:"verification,omitempty"`
	Created      *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=created" json:"created,omitempty"`
	Actioned     *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=actioned" json:"actioned,omitempty"`
}

func (m *InviteStatusResponse) Reset()                    { *m = InviteStatusResponse{} }
func (m *InviteStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*InviteStatusResponse) ProtoMessage()               {}
func (*InviteStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *InviteStatusResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *InviteStatusResponse) GetStatus() InviteStatus {
	if m != nil {
		return m.Status
	}
	return InviteStatus_PENDING
}

func (m *InviteStatusResponse) GetVerification() string {
	if m != nil {
		return m.Verification
	}
	return ""
}

func (m *InviteStatusResponse) GetCreated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *InviteStatusResponse) GetActioned() *google_protobuf.Timestamp {
	if m != nil {
		return m.Actioned
	}
	return nil
}

type ActionInviteRequest struct {
	Email         string       `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	ProjectId     string       `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	DistributorId string       `protobuf:"bytes,3,opt,name=distributor_id,json=distributorId" json:"distributor_id,omitempty"`
	MemberId      string       `protobuf:"bytes,4,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	Status        InviteStatus `protobuf:"varint,5,opt,name=status,enum=project.InviteStatus" json:"status,omitempty"`
	Verification  string       `protobuf:"bytes,6,opt,name=verification" json:"verification,omitempty"`
}

func (m *ActionInviteRequest) Reset()                    { *m = ActionInviteRequest{} }
func (m *ActionInviteRequest) String() string            { return proto.CompactTextString(m) }
func (*ActionInviteRequest) ProtoMessage()               {}
func (*ActionInviteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ActionInviteRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ActionInviteRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *ActionInviteRequest) GetDistributorId() string {
	if m != nil {
		return m.DistributorId
	}
	return ""
}

func (m *ActionInviteRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *ActionInviteRequest) GetStatus() InviteStatus {
	if m != nil {
		return m.Status
	}
	return InviteStatus_PENDING
}

func (m *ActionInviteRequest) GetVerification() string {
	if m != nil {
		return m.Verification
	}
	return ""
}

type MemberStatusResponse struct {
	MemberId      string                     `protobuf:"bytes,1,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	ProjectId     string                     `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	DistributorId string                     `protobuf:"bytes,3,opt,name=distributor_id,json=distributorId" json:"distributor_id,omitempty"`
	Type          MemberType                 `protobuf:"varint,4,opt,name=type,enum=project.MemberType" json:"type,omitempty"`
	Invited       *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=invited" json:"invited,omitempty"`
	Expiry        *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=expiry" json:"expiry,omitempty"`
	Joined        *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=joined" json:"joined,omitempty"`
	Detached      *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=detached" json:"detached,omitempty"`
}

func (m *MemberStatusResponse) Reset()                    { *m = MemberStatusResponse{} }
func (m *MemberStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*MemberStatusResponse) ProtoMessage()               {}
func (*MemberStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MemberStatusResponse) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *MemberStatusResponse) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *MemberStatusResponse) GetDistributorId() string {
	if m != nil {
		return m.DistributorId
	}
	return ""
}

func (m *MemberStatusResponse) GetType() MemberType {
	if m != nil {
		return m.Type
	}
	return MemberType_OWNER
}

func (m *MemberStatusResponse) GetInvited() *google_protobuf.Timestamp {
	if m != nil {
		return m.Invited
	}
	return nil
}

func (m *MemberStatusResponse) GetExpiry() *google_protobuf.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

func (m *MemberStatusResponse) GetJoined() *google_protobuf.Timestamp {
	if m != nil {
		return m.Joined
	}
	return nil
}

func (m *MemberStatusResponse) GetDetached() *google_protobuf.Timestamp {
	if m != nil {
		return m.Detached
	}
	return nil
}

type GetMembersRequest struct {
	ProjectId     string `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	DistributorId string `protobuf:"bytes,2,opt,name=distributor_id,json=distributorId" json:"distributor_id,omitempty"`
}

func (m *GetMembersRequest) Reset()                    { *m = GetMembersRequest{} }
func (m *GetMembersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetMembersRequest) ProtoMessage()               {}
func (*GetMembersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetMembersRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *GetMembersRequest) GetDistributorId() string {
	if m != nil {
		return m.DistributorId
	}
	return ""
}

type GetProjectsRequest struct {
	MemberId      string `protobuf:"bytes,1,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	DistributorId string `protobuf:"bytes,2,opt,name=distributor_id,json=distributorId" json:"distributor_id,omitempty"`
}

func (m *GetProjectsRequest) Reset()                    { *m = GetProjectsRequest{} }
func (m *GetProjectsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProjectsRequest) ProtoMessage()               {}
func (*GetProjectsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetProjectsRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *GetProjectsRequest) GetDistributorId() string {
	if m != nil {
		return m.DistributorId
	}
	return ""
}

type GetInvitesRequest struct {
	MemberId      string `protobuf:"bytes,1,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	DistributorId string `protobuf:"bytes,2,opt,name=distributor_id,json=distributorId" json:"distributor_id,omitempty"`
}

func (m *GetInvitesRequest) Reset()                    { *m = GetInvitesRequest{} }
func (m *GetInvitesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetInvitesRequest) ProtoMessage()               {}
func (*GetInvitesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetInvitesRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *GetInvitesRequest) GetDistributorId() string {
	if m != nil {
		return m.DistributorId
	}
	return ""
}

type InvitesResponse struct {
	Invites []*InviteResponse `protobuf:"bytes,1,rep,name=invites" json:"invites,omitempty"`
}

func (m *InvitesResponse) Reset()                    { *m = InvitesResponse{} }
func (m *InvitesResponse) String() string            { return proto.CompactTextString(m) }
func (*InvitesResponse) ProtoMessage()               {}
func (*InvitesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *InvitesResponse) GetInvites() []*InviteResponse {
	if m != nil {
		return m.Invites
	}
	return nil
}

type InviteResponse struct {
	Project *ProjectResponse      `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
	Status  *InviteStatusResponse `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *InviteResponse) Reset()                    { *m = InviteResponse{} }
func (m *InviteResponse) String() string            { return proto.CompactTextString(m) }
func (*InviteResponse) ProtoMessage()               {}
func (*InviteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *InviteResponse) GetProject() *ProjectResponse {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *InviteResponse) GetStatus() *InviteStatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

type MembersResponse struct {
	Members map[string]*MemberStatusResponse `protobuf:"bytes,1,rep,name=members" json:"members,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MembersResponse) Reset()                    { *m = MembersResponse{} }
func (m *MembersResponse) String() string            { return proto.CompactTextString(m) }
func (*MembersResponse) ProtoMessage()               {}
func (*MembersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *MembersResponse) GetMembers() map[string]*MemberStatusResponse {
	if m != nil {
		return m.Members
	}
	return nil
}

type ProjectsResponse struct {
	Projects map[string]*ProjectResponse `protobuf:"bytes,1,rep,name=projects" json:"projects,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ProjectsResponse) Reset()                    { *m = ProjectsResponse{} }
func (m *ProjectsResponse) String() string            { return proto.CompactTextString(m) }
func (*ProjectsResponse) ProtoMessage()               {}
func (*ProjectsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ProjectsResponse) GetProjects() map[string]*ProjectResponse {
	if m != nil {
		return m.Projects
	}
	return nil
}

type ProjectExistsResponse struct {
	Exists      bool     `protobuf:"varint,1,opt,name=exists" json:"exists,omitempty"`
	Suggestions []string `protobuf:"bytes,2,rep,name=suggestions" json:"suggestions,omitempty"`
}

func (m *ProjectExistsResponse) Reset()                    { *m = ProjectExistsResponse{} }
func (m *ProjectExistsResponse) String() string            { return proto.CompactTextString(m) }
func (*ProjectExistsResponse) ProtoMessage()               {}
func (*ProjectExistsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ProjectExistsResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *ProjectExistsResponse) GetSuggestions() []string {
	if m != nil {
		return m.Suggestions
	}
	return nil
}

type TimezoneRequest struct {
	ProjectId     string `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	DistributorId string `protobuf:"bytes,2,opt,name=distributor_id,json=distributorId" json:"distributor_id,omitempty"`
	Timezone      string `protobuf:"bytes,3,opt,name=timezone" json:"timezone,omitempty"`
}

func (m *TimezoneRequest) Reset()                    { *m = TimezoneRequest{} }
func (m *TimezoneRequest) String() string            { return proto.CompactTextString(m) }
func (*TimezoneRequest) ProtoMessage()               {}
func (*TimezoneRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *TimezoneRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *TimezoneRequest) GetDistributorId() string {
	if m != nil {
		return m.DistributorId
	}
	return ""
}

func (m *TimezoneRequest) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

type TimezoneResponse struct {
	Timezone       string `protobuf:"bytes,1,opt,name=timezone" json:"timezone,omitempty"`
	TimezoneOffset int32  `protobuf:"varint,2,opt,name=timezone_offset,json=timezoneOffset" json:"timezone_offset,omitempty"`
}

func (m *TimezoneResponse) Reset()                    { *m = TimezoneResponse{} }
func (m *TimezoneResponse) String() string            { return proto.CompactTextString(m) }
func (*TimezoneResponse) ProtoMessage()               {}
func (*TimezoneResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *TimezoneResponse) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *TimezoneResponse) GetTimezoneOffset() int32 {
	if m != nil {
		return m.TimezoneOffset
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "project.CreateRequest")
	proto.RegisterType((*RetrieveRequest)(nil), "project.RetrieveRequest")
	proto.RegisterType((*ProjectResponse)(nil), "project.ProjectResponse")
	proto.RegisterType((*AddMemberRequest)(nil), "project.AddMemberRequest")
	proto.RegisterType((*RemoveMemberRequest)(nil), "project.RemoveMemberRequest")
	proto.RegisterType((*InviteRequest)(nil), "project.InviteRequest")
	proto.RegisterType((*InviteStatusResponse)(nil), "project.InviteStatusResponse")
	proto.RegisterType((*ActionInviteRequest)(nil), "project.ActionInviteRequest")
	proto.RegisterType((*MemberStatusResponse)(nil), "project.MemberStatusResponse")
	proto.RegisterType((*GetMembersRequest)(nil), "project.GetMembersRequest")
	proto.RegisterType((*GetProjectsRequest)(nil), "project.GetProjectsRequest")
	proto.RegisterType((*GetInvitesRequest)(nil), "project.GetInvitesRequest")
	proto.RegisterType((*InvitesResponse)(nil), "project.InvitesResponse")
	proto.RegisterType((*InviteResponse)(nil), "project.InviteResponse")
	proto.RegisterType((*MembersResponse)(nil), "project.MembersResponse")
	proto.RegisterType((*ProjectsResponse)(nil), "project.ProjectsResponse")
	proto.RegisterType((*ProjectExistsResponse)(nil), "project.ProjectExistsResponse")
	proto.RegisterType((*TimezoneRequest)(nil), "project.TimezoneRequest")
	proto.RegisterType((*TimezoneResponse)(nil), "project.TimezoneResponse")
	proto.RegisterEnum("project.Mode", Mode_name, Mode_value)
	proto.RegisterEnum("project.Region", Region_name, Region_value)
	proto.RegisterEnum("project.MemberType", MemberType_name, MemberType_value)
	proto.RegisterEnum("project.InviteStatus", InviteStatus_name, InviteStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Projects service

type ProjectsClient interface {
	Exists(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*ProjectExistsResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*ProjectsResponse, error)
	AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error)
	RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error)
	GetMembers(ctx context.Context, in *GetMembersRequest, opts ...grpc.CallOption) (*MembersResponse, error)
	GetInvites(ctx context.Context, in *GetInvitesRequest, opts ...grpc.CallOption) (*InvitesResponse, error)
	Invite(ctx context.Context, in *InviteRequest, opts ...grpc.CallOption) (*InviteStatusResponse, error)
	ActionInvite(ctx context.Context, in *ActionInviteRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error)
	SetTimezone(ctx context.Context, in *TimezoneRequest, opts ...grpc.CallOption) (*TimezoneResponse, error)
}

type projectsClient struct {
	cc *grpc.ClientConn
}

func NewProjectsClient(cc *grpc.ClientConn) ProjectsClient {
	return &projectsClient{cc}
}

func (c *projectsClient) Exists(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*ProjectExistsResponse, error) {
	out := new(ProjectExistsResponse)
	err := grpc.Invoke(ctx, "/project.Projects/Exists", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	out := new(ProjectResponse)
	err := grpc.Invoke(ctx, "/project.Projects/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	out := new(ProjectResponse)
	err := grpc.Invoke(ctx, "/project.Projects/Retrieve", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*ProjectsResponse, error) {
	out := new(ProjectsResponse)
	err := grpc.Invoke(ctx, "/project.Projects/GetProjects", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error) {
	out := new(MemberStatusResponse)
	err := grpc.Invoke(ctx, "/project.Projects/AddMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error) {
	out := new(MemberStatusResponse)
	err := grpc.Invoke(ctx, "/project.Projects/RemoveMember", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) GetMembers(ctx context.Context, in *GetMembersRequest, opts ...grpc.CallOption) (*MembersResponse, error) {
	out := new(MembersResponse)
	err := grpc.Invoke(ctx, "/project.Projects/GetMembers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) GetInvites(ctx context.Context, in *GetInvitesRequest, opts ...grpc.CallOption) (*InvitesResponse, error) {
	out := new(InvitesResponse)
	err := grpc.Invoke(ctx, "/project.Projects/GetInvites", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) Invite(ctx context.Context, in *InviteRequest, opts ...grpc.CallOption) (*InviteStatusResponse, error) {
	out := new(InviteStatusResponse)
	err := grpc.Invoke(ctx, "/project.Projects/Invite", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) ActionInvite(ctx context.Context, in *ActionInviteRequest, opts ...grpc.CallOption) (*MemberStatusResponse, error) {
	out := new(MemberStatusResponse)
	err := grpc.Invoke(ctx, "/project.Projects/ActionInvite", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) SetTimezone(ctx context.Context, in *TimezoneRequest, opts ...grpc.CallOption) (*TimezoneResponse, error) {
	out := new(TimezoneResponse)
	err := grpc.Invoke(ctx, "/project.Projects/SetTimezone", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Projects service

type ProjectsServer interface {
	Exists(context.Context, *RetrieveRequest) (*ProjectExistsResponse, error)
	Create(context.Context, *CreateRequest) (*ProjectResponse, error)
	Retrieve(context.Context, *RetrieveRequest) (*ProjectResponse, error)
	GetProjects(context.Context, *GetProjectsRequest) (*ProjectsResponse, error)
	AddMember(context.Context, *AddMemberRequest) (*MemberStatusResponse, error)
	RemoveMember(context.Context, *RemoveMemberRequest) (*MemberStatusResponse, error)
	GetMembers(context.Context, *GetMembersRequest) (*MembersResponse, error)
	GetInvites(context.Context, *GetInvitesRequest) (*InvitesResponse, error)
	Invite(context.Context, *InviteRequest) (*InviteStatusResponse, error)
	ActionInvite(context.Context, *ActionInviteRequest) (*MemberStatusResponse, error)
	SetTimezone(context.Context, *TimezoneRequest) (*TimezoneResponse, error)
}

func RegisterProjectsServer(s *grpc.Server, srv ProjectsServer) {
	s.RegisterService(&_Projects_serviceDesc, srv)
}

func _Projects_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.Projects/Exists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).Exists(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.Projects/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.Projects/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).Retrieve(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.Projects/GetProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).GetProjects(ctx, req.(*GetProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.Projects/AddMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).AddMember(ctx, req.(*AddMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.Projects/RemoveMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).RemoveMember(ctx, req.(*RemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_GetMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).GetMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.Projects/GetMembers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).GetMembers(ctx, req.(*GetMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_GetInvites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).GetInvites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.Projects/GetInvites",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).GetInvites(ctx, req.(*GetInvitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_Invite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).Invite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.Projects/Invite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).Invite(ctx, req.(*InviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_ActionInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).ActionInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.Projects/ActionInvite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).ActionInvite(ctx, req.(*ActionInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_SetTimezone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimezoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).SetTimezone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.Projects/SetTimezone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).SetTimezone(ctx, req.(*TimezoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Projects_serviceDesc = grpc.ServiceDesc{
	ServiceName: "project.Projects",
	HandlerType: (*ProjectsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exists",
			Handler:    _Projects_Exists_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Projects_Create_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _Projects_Retrieve_Handler,
		},
		{
			MethodName: "GetProjects",
			Handler:    _Projects_GetProjects_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _Projects_AddMember_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _Projects_RemoveMember_Handler,
		},
		{
			MethodName: "GetMembers",
			Handler:    _Projects_GetMembers_Handler,
		},
		{
			MethodName: "GetInvites",
			Handler:    _Projects_GetInvites_Handler,
		},
		{
			MethodName: "Invite",
			Handler:    _Projects_Invite_Handler,
		},
		{
			MethodName: "ActionInvite",
			Handler:    _Projects_ActionInvite_Handler,
		},
		{
			MethodName: "SetTimezone",
			Handler:    _Projects_SetTimezone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "project.proto",
}

func init() { proto.RegisterFile("project.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x58, 0xdd, 0x72, 0xda, 0x46,
	0x14, 0xb6, 0x04, 0x08, 0x38, 0x18, 0x50, 0x37, 0x4e, 0x4a, 0x95, 0xa6, 0x25, 0xea, 0x64, 0xec,
	0xf1, 0x4c, 0xf0, 0x84, 0xa4, 0x3f, 0x93, 0xe9, 0x34, 0xc3, 0x8f, 0xea, 0xa1, 0x8d, 0x81, 0x2e,
	0x10, 0x3b, 0xbd, 0xa8, 0x47, 0xa0, 0x35, 0x51, 0x62, 0x10, 0x45, 0xc2, 0x63, 0xb7, 0xcf, 0xd4,
	0xde, 0x76, 0xfa, 0x06, 0xbd, 0xee, 0x1b, 0xf4, 0x01, 0x7a, 0xdf, 0xbb, 0x76, 0xb4, 0xd2, 0x8a,
	0x95, 0x2c, 0x1b, 0xa6, 0xe3, 0xc9, 0xb4, 0x77, 0xec, 0xd9, 0xb3, 0xbb, 0xe7, 0x7c, 0xe7, 0xdb,
	0xb3, 0x9f, 0x80, 0xfc, 0x6c, 0x6e, 0xbd, 0x26, 0x23, 0xa7, 0x32, 0x9b, 0x5b, 0x8e, 0x85, 0xd2,
	0xfe, 0x50, 0xf9, 0x70, 0x6c, 0x59, 0xe3, 0x53, 0xb2, 0x47, 0xcd, 0xc3, 0xc5, 0xc9, 0x9e, 0x63,
	0x4e, 0x88, 0xed, 0xe8, 0x93, 0x99, 0xe7, 0xa9, 0xfe, 0x22, 0x42, 0xbe, 0x31, 0x27, 0xba, 0x43,
	0x30, 0xf9, 0x7e, 0x41, 0x6c, 0x07, 0x6d, 0x41, 0x4a, 0x3f, 0x35, 0x75, 0xbb, 0x24, 0x94, 0x85,
	0x9d, 0x2c, 0xf6, 0x06, 0xe8, 0x01, 0x14, 0x0c, 0xd3, 0x76, 0xe6, 0xe6, 0x70, 0xe1, 0x58, 0xf3,
	0x63, 0xd3, 0x28, 0x89, 0x74, 0x3a, 0xcf, 0x59, 0x5b, 0x06, 0x42, 0x90, 0x9c, 0xea, 0x13, 0x52,
	0x4a, 0xd0, 0x49, 0xfa, 0x1b, 0xdd, 0x87, 0xe4, 0xc4, 0x32, 0x48, 0x29, 0x59, 0x16, 0x76, 0x0a,
	0xd5, 0x7c, 0x85, 0x85, 0x7a, 0x60, 0x19, 0x04, 0xd3, 0x29, 0xb4, 0x0d, 0xd2, 0x9c, 0x8c, 0x4d,
	0x6b, 0x5a, 0x4a, 0x51, 0xa7, 0x62, 0xe0, 0x84, 0xa9, 0x19, 0xfb, 0xd3, 0xe8, 0x09, 0x24, 0x27,
	0xc4, 0xd1, 0x4b, 0x52, 0x39, 0xb1, 0x93, 0xab, 0x96, 0x03, 0xb7, 0x50, 0x0a, 0x95, 0x03, 0xe2,
	0xe8, 0xda, 0xd4, 0x99, 0x5f, 0x60, 0xea, 0x8d, 0x14, 0xc8, 0xb8, 0x79, 0xff, 0x60, 0x4d, 0x49,
	0x29, 0x4d, 0x23, 0x0b, 0xc6, 0xca, 0xa7, 0x90, 0x0d, 0xdc, 0x91, 0x0c, 0x89, 0x37, 0xe4, 0xc2,
	0xcf, 0xdc, 0xfd, 0xe9, 0xa2, 0x71, 0xa6, 0x9f, 0x2e, 0x88, 0x9f, 0xae, 0x37, 0x78, 0x2a, 0x7e,
	0x26, 0xa8, 0xdf, 0x41, 0x11, 0x13, 0x67, 0x6e, 0x92, 0xb3, 0x00, 0xba, 0x02, 0x88, 0xa6, 0xe1,
	0xaf, 0x16, 0x4d, 0x63, 0x5d, 0xd0, 0x02, 0xc4, 0x13, 0x1c, 0xe2, 0xea, 0xaf, 0x22, 0x14, 0xbb,
	0x5e, 0x7a, 0x98, 0xd8, 0x33, 0x6b, 0x6a, 0x93, 0x1b, 0x3d, 0x20, 0xa8, 0x55, 0x32, 0xa6, 0x56,
	0xa9, 0x75, 0x6a, 0x25, 0xad, 0xaa, 0x55, 0x7a, 0x44, 0xcb, 0x62, 0x50, 0xd0, 0x73, 0x55, 0xa5,
	0xe2, 0xb1, 0xb1, 0xc2, 0xd8, 0x58, 0xe9, 0x33, 0x36, 0x62, 0xe6, 0x1a, 0xaa, 0x55, 0x26, 0x5c,
	0x2b, 0xb4, 0x0d, 0x45, 0xf6, 0xfb, 0xd8, 0x3a, 0x39, 0xb1, 0x89, 0x53, 0xca, 0x96, 0x85, 0x9d,
	0x14, 0x2e, 0x30, 0x73, 0x87, 0x5a, 0xd5, 0xdf, 0x05, 0x90, 0x6b, 0x86, 0x71, 0x40, 0x26, 0x43,
	0x32, 0x67, 0xd5, 0xb9, 0x0b, 0xd9, 0x09, 0x35, 0x1c, 0x07, 0x18, 0x66, 0x3c, 0x43, 0xcb, 0x40,
	0xf7, 0x00, 0xfc, 0x34, 0x96, 0x28, 0x66, 0x7d, 0x4b, 0x2b, 0x0e, 0xe8, 0x44, 0x1c, 0xd0, 0xdb,
	0x90, 0x74, 0x2e, 0x66, 0x8c, 0xea, 0xb7, 0x96, 0xf0, 0xd1, 0x63, 0xfa, 0x17, 0x33, 0x82, 0xa9,
	0x03, 0xaa, 0x82, 0x44, 0xce, 0x67, 0xe6, 0xfc, 0x82, 0x22, 0x7d, 0x3d, 0x34, 0xbe, 0xa7, 0x7a,
	0x0e, 0xb7, 0x30, 0x99, 0x58, 0x67, 0xe4, 0x6d, 0xa7, 0xa5, 0xfe, 0x26, 0x40, 0xbe, 0x35, 0x3d,
	0x33, 0x43, 0x4d, 0x82, 0x4c, 0x74, 0xf3, 0x94, 0x35, 0x09, 0x3a, 0xf8, 0x3f, 0x80, 0xf8, 0xa7,
	0x00, 0x5b, 0x5e, 0x2a, 0x3d, 0x47, 0x77, 0x16, 0x76, 0x70, 0xb5, 0xe2, 0x33, 0x7a, 0x08, 0x92,
	0x4d, 0xfd, 0x68, 0x36, 0x85, 0xea, 0xed, 0x20, 0x9a, 0xd0, 0x26, 0xbe, 0x13, 0x52, 0x61, 0xf3,
	0x8c, 0xcc, 0xcd, 0x13, 0x73, 0xa4, 0x3b, 0xee, 0x0d, 0xf1, 0xf2, 0x0b, 0xd9, 0xf8, 0x6b, 0x91,
	0x5c, 0xff, 0x5a, 0x7c, 0x02, 0x19, 0x7d, 0xe4, 0xae, 0x27, 0xc6, 0x1a, 0xd9, 0x06, 0xbe, 0xea,
	0x1f, 0x02, 0xdc, 0xaa, 0xd1, 0xc1, 0xdb, 0x2b, 0x60, 0x88, 0x91, 0xc9, 0x08, 0x23, 0x97, 0x88,
	0xa6, 0xfe, 0x0d, 0xa2, 0xd2, 0x65, 0x44, 0xd5, 0xbf, 0x44, 0xd8, 0xf2, 0xc8, 0x11, 0xa9, 0xe9,
	0x7f, 0xe9, 0xc6, 0x3f, 0x81, 0xb4, 0x49, 0x13, 0x5c, 0xa7, 0x7e, 0xcc, 0x95, 0xa3, 0xb8, 0xb4,
	0x2e, 0xc5, 0xdd, 0x35, 0xaf, 0x2d, 0x73, 0xba, 0x56, 0xdb, 0xf5, 0x3d, 0x5d, 0x7a, 0x19, 0xc4,
	0xd1, 0x47, 0xaf, 0x88, 0x41, 0xbb, 0xee, 0x0a, 0x7a, 0x31, 0x5f, 0xf5, 0x25, 0xbc, 0xb3, 0x4f,
	0x1c, 0x2f, 0x59, 0x9b, 0x71, 0x2b, 0x8c, 0xac, 0xb0, 0x1a, 0xd9, 0xb8, 0x47, 0x4b, 0x3d, 0x02,
	0xb4, 0x4f, 0x1c, 0xff, 0x05, 0xb4, 0xd7, 0xea, 0x76, 0x6b, 0xee, 0x7c, 0x48, 0x83, 0xf6, 0xe8,
	0x76, 0xa3, 0x1b, 0x37, 0xa1, 0x18, 0xec, 0xea, 0x53, 0xf0, 0x11, 0x2b, 0xbb, 0xab, 0xa7, 0x5c,
	0xcd, 0xf2, 0x6e, 0x84, 0xef, 0xcc, 0x93, 0xd5, 0xdc, 0x56, 0x7f, 0x84, 0x42, 0x78, 0x0a, 0x55,
	0x81, 0x09, 0x3a, 0x1a, 0x59, 0xae, 0x5a, 0x0a, 0x36, 0x89, 0x28, 0x04, 0xcc, 0x1c, 0xd1, 0xc7,
	0xa1, 0xce, 0x95, 0xab, 0xde, 0x8b, 0xbf, 0x67, 0x6c, 0x9d, 0xef, 0xac, 0xfe, 0x24, 0x40, 0x31,
	0x28, 0xa7, 0x7f, 0xfc, 0x33, 0x48, 0x7b, 0x48, 0xb0, 0x1c, 0x1e, 0x44, 0x68, 0x1e, 0xb8, 0xb2,
	0xb1, 0x27, 0xbe, 0xd8, 0x2a, 0xe5, 0x25, 0x6c, 0xf2, 0x13, 0x31, 0x32, 0xeb, 0x31, 0x2f, 0xb3,
	0xf8, 0x60, 0xe3, 0xee, 0x35, 0xaf, 0xc2, 0x7e, 0x16, 0x40, 0x5e, 0x72, 0xc4, 0x0f, 0xb8, 0x01,
	0x19, 0x7f, 0x3d, 0x8b, 0x78, 0x3b, 0x0a, 0xd8, 0x32, 0x64, 0x66, 0xf0, 0x62, 0x0e, 0x16, 0x2a,
	0x03, 0xc8, 0x87, 0xa6, 0x62, 0xa2, 0xae, 0x84, 0xa3, 0xbe, 0xba, 0x2a, 0x5c, 0xc0, 0xdf, 0xc0,
	0x6d, 0x7f, 0x56, 0x3b, 0x37, 0x6d, 0x2e, 0xe8, 0x3b, 0xee, 0x55, 0x77, 0x2d, 0xf4, 0x84, 0x0c,
	0xf6, 0x47, 0xa8, 0x0c, 0x39, 0x7b, 0x31, 0x1e, 0x13, 0xdb, 0xed, 0x75, 0x6e, 0x35, 0x13, 0x3b,
	0x59, 0xcc, 0x9b, 0x54, 0x1b, 0x8a, 0x7d, 0x5f, 0xff, 0xdc, 0xe8, 0x15, 0x0c, 0x69, 0xb1, 0x44,
	0x58, 0x8b, 0xa9, 0x87, 0x20, 0x2f, 0x0f, 0xf5, 0x53, 0xe0, 0xfd, 0x85, 0xd5, 0xda, 0x4d, 0x8c,
	0xd3, 0x6e, 0xbb, 0x8f, 0x20, 0xe9, 0xaa, 0x4d, 0x94, 0x83, 0x74, 0xaf, 0xd6, 0x6e, 0xd6, 0x3b,
	0x47, 0xf2, 0x06, 0x2a, 0x00, 0x74, 0x71, 0xa7, 0x39, 0x68, 0xf4, 0x5b, 0x9d, 0xb6, 0x2c, 0xa0,
	0x4d, 0xc8, 0x60, 0xad, 0xa7, 0xe1, 0x17, 0x5a, 0x53, 0x16, 0x77, 0xab, 0x20, 0x79, 0xda, 0x13,
	0x01, 0x48, 0xfb, 0xcf, 0x3b, 0xf5, 0xda, 0x73, 0x79, 0x03, 0x49, 0x20, 0x0e, 0x7a, 0xb2, 0xe0,
	0xda, 0xb4, 0x01, 0xee, 0x74, 0x35, 0x59, 0x44, 0x19, 0x48, 0xd6, 0x7a, 0xad, 0x9a, 0x9c, 0xd8,
	0xfd, 0x1c, 0x60, 0xd9, 0xa3, 0x51, 0x16, 0x52, 0x9d, 0xc3, 0xb6, 0x86, 0xe5, 0x0d, 0xd7, 0xfd,
	0x40, 0x3b, 0xa8, 0x6b, 0xd8, 0x5b, 0xfa, 0xa2, 0xa5, 0x1d, 0x6a, 0x58, 0x16, 0x69, 0x3c, 0x83,
	0x6e, 0xb7, 0x83, 0xfb, 0x72, 0x62, 0xb7, 0x07, 0x9b, 0xfc, 0x35, 0x72, 0x27, 0xbb, 0x5a, 0xbb,
	0xd9, 0x6a, 0xef, 0xcb, 0x1b, 0x6e, 0x70, 0xb5, 0x46, 0x43, 0xeb, 0xf6, 0xb5, 0x26, 0x0b, 0xf5,
	0x2b, 0xad, 0xe1, 0x8e, 0xe8, 0x2e, 0xda, 0x51, 0xb7, 0x85, 0xb5, 0xa6, 0x9c, 0x40, 0x79, 0xc8,
	0xb6, 0x3b, 0xfd, 0xe3, 0x2f, 0x3b, 0x83, 0x76, 0x53, 0x4e, 0x56, 0xff, 0x4e, 0x41, 0x86, 0x51,
	0x0e, 0xd5, 0x41, 0xf2, 0x08, 0x82, 0x4a, 0x9c, 0xc0, 0x0e, 0x7d, 0x6f, 0x28, 0x1f, 0x44, 0x09,
	0x17, 0xa1, 0xd4, 0x53, 0x90, 0xbc, 0x0f, 0x23, 0x74, 0x27, 0xfe, 0x4b, 0x49, 0xb9, 0x92, 0xb2,
	0xe8, 0x0b, 0xc8, 0xb0, 0xe3, 0xae, 0x89, 0xe0, 0xea, 0xf5, 0x1a, 0xe4, 0xb8, 0xf6, 0x8d, 0xee,
	0x06, 0x8e, 0x97, 0x9b, 0xba, 0xf2, 0xde, 0x95, 0xb7, 0x13, 0x69, 0x90, 0x0d, 0x84, 0x3c, 0x5a,
	0xfa, 0x45, 0xc5, 0xbd, 0x72, 0x7d, 0xc7, 0x40, 0x5f, 0xc3, 0x26, 0xaf, 0x9d, 0xd1, 0xfb, 0x5c,
	0x46, 0x97, 0x24, 0xf5, 0xaa, 0xcd, 0xea, 0x00, 0xcb, 0x47, 0x0f, 0x29, 0x7c, 0x66, 0xe1, 0x97,
	0x90, 0x83, 0x27, 0xda, 0x53, 0xbd, 0x3d, 0xfc, 0xd7, 0x22, 0xbc, 0x47, 0xf8, 0x61, 0xe2, 0xf6,
	0x88, 0xbe, 0x2d, 0xcf, 0x40, 0xf2, 0x4c, 0x5c, 0x79, 0x43, 0x2a, 0x4f, 0xb9, 0xbe, 0xe9, 0xbb,
	0xa8, 0xf0, 0xda, 0x90, 0x43, 0x25, 0x46, 0x32, 0xae, 0x46, 0x25, 0xd7, 0x23, 0x0e, 0xeb, 0x09,
	0x1c, 0x67, 0x22, 0xbd, 0x89, 0xab, 0x76, 0xb4, 0x81, 0xd4, 0x3f, 0xfa, 0xf6, 0xfe, 0xd8, 0x74,
	0x5e, 0x2d, 0x86, 0x95, 0x91, 0x35, 0xd9, 0x7b, 0xb3, 0x18, 0x92, 0x73, 0xef, 0xaf, 0x8b, 0x87,
	0x63, 0x6b, 0xcf, 0x5f, 0x35, 0x94, 0xa8, 0xe5, 0xf1, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0f,
	0xc2, 0x07, 0xa5, 0xf4, 0x10, 0x00, 0x00,
}
