// Code generated by protoc-gen-go.
// source: sights.proto
// DO NOT EDIT!

/*
Package pbsights is a generated protocol buffer package.

It is generated from these files:
	sights.proto

It has these top-level messages:
	TrafficSource
	SightSource
	Sight
	SightResponse
*/
package pbsights

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SourceType int32

const (
	SourceType_Web        SourceType = 0
	SourceType_Mobile     SourceType = 1
	SourceType_API        SourceType = 2
	SourceType_Phone      SourceType = 3
	SourceType_Real_World SourceType = 4
	SourceType_Webhook    SourceType = 5
	SourceType_Other      SourceType = 6
)

var SourceType_name = map[int32]string{
	0: "Web",
	1: "Mobile",
	2: "API",
	3: "Phone",
	4: "Real_World",
	5: "Webhook",
	6: "Other",
}
var SourceType_value = map[string]int32{
	"Web":        0,
	"Mobile":     1,
	"API":        2,
	"Phone":      3,
	"Real_World": 4,
	"Webhook":    5,
	"Other":      6,
}

func (x SourceType) String() string {
	return proto.EnumName(SourceType_name, int32(x))
}
func (SourceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SightType int32

const (
	SightType_Event    SightType = 0
	SightType_Property SightType = 1
	SightType_Heatmap  SightType = 2
	SightType_Form     SightType = 3
	SightType_Generic  SightType = 4
)

var SightType_name = map[int32]string{
	0: "Event",
	1: "Property",
	2: "Heatmap",
	3: "Form",
	4: "Generic",
}
var SightType_value = map[string]int32{
	"Event":    0,
	"Property": 1,
	"Heatmap":  2,
	"Form":     3,
	"Generic":  4,
}

func (x SightType) String() string {
	return proto.EnumName(SightType_name, int32(x))
}
func (SightType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type TrafficSource struct {
	// utm_source
	Source string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	// utm_medium
	Channel    string `protobuf:"bytes,2,opt,name=channel" json:"channel,omitempty"`
	SubChannel string `protobuf:"bytes,3,opt,name=sub_channel,json=subChannel" json:"sub_channel,omitempty"`
	// utm_name
	Campaign string `protobuf:"bytes,4,opt,name=campaign" json:"campaign,omitempty"`
	// utm_term
	Term        string           `protobuf:"bytes,5,opt,name=term" json:"term,omitempty"`
	Creative    string           `protobuf:"bytes,6,opt,name=creative" json:"creative,omitempty"`
	Offer       string           `protobuf:"bytes,7,opt,name=offer" json:"offer,omitempty"`
	TrackingIds map[int32]string `protobuf:"bytes,8,rep,name=tracking_ids,json=trackingIds" json:"tracking_ids,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *TrafficSource) Reset()                    { *m = TrafficSource{} }
func (m *TrafficSource) String() string            { return proto.CompactTextString(m) }
func (*TrafficSource) ProtoMessage()               {}
func (*TrafficSource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TrafficSource) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *TrafficSource) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *TrafficSource) GetSubChannel() string {
	if m != nil {
		return m.SubChannel
	}
	return ""
}

func (m *TrafficSource) GetCampaign() string {
	if m != nil {
		return m.Campaign
	}
	return ""
}

func (m *TrafficSource) GetTerm() string {
	if m != nil {
		return m.Term
	}
	return ""
}

func (m *TrafficSource) GetCreative() string {
	if m != nil {
		return m.Creative
	}
	return ""
}

func (m *TrafficSource) GetOffer() string {
	if m != nil {
		return m.Offer
	}
	return ""
}

func (m *TrafficSource) GetTrackingIds() map[int32]string {
	if m != nil {
		return m.TrackingIds
	}
	return nil
}

type SightSource struct {
	DeviceId         string                     `protobuf:"bytes,1,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	SessionId        string                     `protobuf:"bytes,2,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	IdentityId       string                     `protobuf:"bytes,3,opt,name=identity_id,json=identityId" json:"identity_id,omitempty"`
	TrackerId        string                     `protobuf:"bytes,4,opt,name=tracker_id,json=trackerId" json:"tracker_id,omitempty"`
	RequestId        string                     `protobuf:"bytes,5,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	ProfileVendor    string                     `protobuf:"bytes,6,opt,name=profile_vendor,json=profileVendor" json:"profile_vendor,omitempty"`
	SourceType       SourceType                 `protobuf:"varint,7,opt,name=source_type,json=sourceType,enum=pbsights.SourceType" json:"source_type,omitempty"`
	Hostname         string                     `protobuf:"bytes,8,opt,name=hostname" json:"hostname,omitempty"`
	Ip               string                     `protobuf:"bytes,9,opt,name=ip" json:"ip,omitempty"`
	UserAgent        string                     `protobuf:"bytes,10,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
	Interactions     map[string]int32           `protobuf:"bytes,11,rep,name=interactions" json:"interactions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RequestStartTime *google_protobuf.Timestamp `protobuf:"bytes,12,opt,name=request_start_time,json=requestStartTime" json:"request_start_time,omitempty"`
	TrafficSource    *TrafficSource             `protobuf:"bytes,13,opt,name=traffic_source,json=trafficSource" json:"traffic_source,omitempty"`
}

func (m *SightSource) Reset()                    { *m = SightSource{} }
func (m *SightSource) String() string            { return proto.CompactTextString(m) }
func (*SightSource) ProtoMessage()               {}
func (*SightSource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SightSource) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *SightSource) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *SightSource) GetIdentityId() string {
	if m != nil {
		return m.IdentityId
	}
	return ""
}

func (m *SightSource) GetTrackerId() string {
	if m != nil {
		return m.TrackerId
	}
	return ""
}

func (m *SightSource) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *SightSource) GetProfileVendor() string {
	if m != nil {
		return m.ProfileVendor
	}
	return ""
}

func (m *SightSource) GetSourceType() SourceType {
	if m != nil {
		return m.SourceType
	}
	return SourceType_Web
}

func (m *SightSource) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *SightSource) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *SightSource) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *SightSource) GetInteractions() map[string]int32 {
	if m != nil {
		return m.Interactions
	}
	return nil
}

func (m *SightSource) GetRequestStartTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.RequestStartTime
	}
	return nil
}

func (m *SightSource) GetTrafficSource() *TrafficSource {
	if m != nil {
		return m.TrafficSource
	}
	return nil
}

type Sight struct {
	ProfileNamespace string                     `protobuf:"bytes,1,opt,name=profile_namespace,json=profileNamespace" json:"profile_namespace,omitempty"`
	ProfileId        string                     `protobuf:"bytes,2,opt,name=profile_id,json=profileId" json:"profile_id,omitempty"`
	Source           *SightSource               `protobuf:"bytes,3,opt,name=source" json:"source,omitempty"`
	Time             *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=time" json:"time,omitempty"`
	Type             SightType                  `protobuf:"varint,5,opt,name=type,enum=pbsights.SightType" json:"type,omitempty"`
	JsonLd           string                     `protobuf:"bytes,6,opt,name=json_ld,json=jsonLd" json:"json_ld,omitempty"`
	Properties       map[string]string          `protobuf:"bytes,7,rep,name=properties" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Meta             map[string]string          `protobuf:"bytes,8,rep,name=meta" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Sight) Reset()                    { *m = Sight{} }
func (m *Sight) String() string            { return proto.CompactTextString(m) }
func (*Sight) ProtoMessage()               {}
func (*Sight) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Sight) GetProfileNamespace() string {
	if m != nil {
		return m.ProfileNamespace
	}
	return ""
}

func (m *Sight) GetProfileId() string {
	if m != nil {
		return m.ProfileId
	}
	return ""
}

func (m *Sight) GetSource() *SightSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Sight) GetTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Sight) GetType() SightType {
	if m != nil {
		return m.Type
	}
	return SightType_Event
}

func (m *Sight) GetJsonLd() string {
	if m != nil {
		return m.JsonLd
	}
	return ""
}

func (m *Sight) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Sight) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

type SightResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	SightId string `protobuf:"bytes,2,opt,name=sight_id,json=sightId" json:"sight_id,omitempty"`
}

func (m *SightResponse) Reset()                    { *m = SightResponse{} }
func (m *SightResponse) String() string            { return proto.CompactTextString(m) }
func (*SightResponse) ProtoMessage()               {}
func (*SightResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SightResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SightResponse) GetSightId() string {
	if m != nil {
		return m.SightId
	}
	return ""
}

func init() {
	proto.RegisterType((*TrafficSource)(nil), "pbsights.TrafficSource")
	proto.RegisterType((*SightSource)(nil), "pbsights.SightSource")
	proto.RegisterType((*Sight)(nil), "pbsights.Sight")
	proto.RegisterType((*SightResponse)(nil), "pbsights.SightResponse")
	proto.RegisterEnum("pbsights.SourceType", SourceType_name, SourceType_value)
	proto.RegisterEnum("pbsights.SightType", SightType_name, SightType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Sights service

type SightsClient interface {
	Write(ctx context.Context, in *Sight, opts ...grpc.CallOption) (*SightResponse, error)
}

type sightsClient struct {
	cc *grpc.ClientConn
}

func NewSightsClient(cc *grpc.ClientConn) SightsClient {
	return &sightsClient{cc}
}

func (c *sightsClient) Write(ctx context.Context, in *Sight, opts ...grpc.CallOption) (*SightResponse, error) {
	out := new(SightResponse)
	err := grpc.Invoke(ctx, "/pbsights.Sights/Write", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Sights service

type SightsServer interface {
	Write(context.Context, *Sight) (*SightResponse, error)
}

func RegisterSightsServer(s *grpc.Server, srv SightsServer) {
	s.RegisterService(&_Sights_serviceDesc, srv)
}

func _Sights_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Sight)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SightsServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbsights.Sights/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SightsServer).Write(ctx, req.(*Sight))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sights_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbsights.Sights",
	HandlerType: (*SightsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _Sights_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sights.proto",
}

func init() { proto.RegisterFile("sights.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 884 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x55, 0xff, 0x6e, 0x1b, 0x45,
	0x10, 0xae, 0xed, 0xf3, 0x8f, 0x1b, 0x27, 0xee, 0x75, 0x29, 0xe4, 0x6a, 0x84, 0x12, 0x45, 0x42,
	0xb5, 0x82, 0x72, 0x11, 0x41, 0x08, 0x04, 0xa2, 0x55, 0x81, 0x42, 0x2c, 0x28, 0x44, 0x4e, 0x44,
	0x24, 0x24, 0x74, 0x5a, 0xdf, 0x8d, 0xed, 0x25, 0xf6, 0xed, 0xb1, 0xbb, 0xb6, 0xe4, 0xc7, 0xe4,
	0x7f, 0x5e, 0x80, 0xb7, 0x40, 0x3b, 0xbb, 0x67, 0xbb, 0xa6, 0xa8, 0xe2, 0xbf, 0x9b, 0x6f, 0xbe,
	0x19, 0xcf, 0x7c, 0x33, 0xb3, 0x86, 0x03, 0x2d, 0xa6, 0x33, 0xa3, 0x93, 0x52, 0x49, 0x23, 0x59,
	0xa7, 0x1c, 0x3b, 0xbb, 0x7f, 0x3c, 0x95, 0x72, 0x3a, 0xc7, 0x0b, 0xc2, 0xc7, 0xcb, 0xc9, 0x85,
	0x11, 0x0b, 0xd4, 0x86, 0x2f, 0x4a, 0x47, 0x3d, 0xfd, 0xb3, 0x0e, 0x87, 0xb7, 0x8a, 0x4f, 0x26,
	0x22, 0xbb, 0x91, 0x4b, 0x95, 0x21, 0x7b, 0x0f, 0x5a, 0x9a, 0xbe, 0xe2, 0xda, 0x49, 0x6d, 0x10,
	0x8e, 0xbc, 0xc5, 0x62, 0x68, 0x67, 0x33, 0x5e, 0x14, 0x38, 0x8f, 0xeb, 0xe4, 0xa8, 0x4c, 0x76,
	0x0c, 0x5d, 0xbd, 0x1c, 0xa7, 0x95, 0xb7, 0x41, 0x5e, 0xd0, 0xcb, 0xf1, 0x37, 0x9e, 0xd0, 0x87,
	0x4e, 0xc6, 0x17, 0x25, 0x17, 0xd3, 0x22, 0x0e, 0xc8, 0xbb, 0xb1, 0x19, 0x83, 0xc0, 0xa0, 0x5a,
	0xc4, 0x4d, 0xc2, 0xe9, 0x9b, 0xf8, 0x0a, 0xb9, 0x11, 0x2b, 0x8c, 0x5b, 0x9e, 0xef, 0x6d, 0xf6,
	0x18, 0x9a, 0x72, 0x32, 0x41, 0x15, 0xb7, 0xc9, 0xe1, 0x0c, 0xf6, 0x03, 0x1c, 0x18, 0xc5, 0xb3,
	0x7b, 0x51, 0x4c, 0x53, 0x91, 0xeb, 0xb8, 0x73, 0xd2, 0x18, 0x74, 0x2f, 0x07, 0x49, 0x25, 0x44,
	0xf2, 0x5a, 0x8f, 0xd6, 0x22, 0xee, 0x30, 0xd7, 0x2f, 0x0b, 0xa3, 0xd6, 0xa3, 0xae, 0xd9, 0x22,
	0xfd, 0x67, 0x10, 0xed, 0x13, 0x58, 0x04, 0x8d, 0x7b, 0x5c, 0x93, 0x24, 0xcd, 0x91, 0xfd, 0xb4,
	0x85, 0xac, 0xf8, 0x7c, 0x89, 0x5e, 0x0d, 0x67, 0x7c, 0x51, 0xff, 0xbc, 0x76, 0xfa, 0x77, 0x00,
	0xdd, 0x1b, 0xfb, 0xb3, 0x5e, 0xd1, 0xf7, 0x21, 0xcc, 0x71, 0x25, 0x32, 0x4c, 0x45, 0xee, 0x45,
	0xed, 0x38, 0x60, 0x98, 0xb3, 0x0f, 0x00, 0x34, 0x6a, 0x2d, 0x64, 0x61, 0xbd, 0x2e, 0x57, 0xe8,
	0x91, 0x61, 0x6e, 0xb5, 0x15, 0x39, 0x16, 0x46, 0x98, 0xb5, 0xf5, 0x7b, 0x6d, 0x2b, 0xc8, 0xc5,
	0x53, 0xed, 0xa8, 0xac, 0xdf, 0xa9, 0x1b, 0x7a, 0xc4, 0xb9, 0x15, 0xfe, 0xb1, 0x44, 0x6d, 0xac,
	0xdb, 0x89, 0x1c, 0x7a, 0x64, 0x98, 0xb3, 0x0f, 0xa1, 0x57, 0x2a, 0x39, 0x11, 0x73, 0x4c, 0x57,
	0x58, 0xe4, 0x52, 0x79, 0xbd, 0x0f, 0x3d, 0xfa, 0x0b, 0x81, 0xec, 0x53, 0xe8, 0xba, 0x2d, 0x48,
	0xcd, 0xba, 0x44, 0x92, 0xbe, 0x77, 0xf9, 0x78, 0xab, 0xae, 0x6b, 0xf4, 0x76, 0x5d, 0xe2, 0x08,
	0xf4, 0xe6, 0xdb, 0xce, 0x71, 0x26, 0xb5, 0x29, 0xf8, 0x02, 0xe3, 0x8e, 0xeb, 0xbb, 0xb2, 0x59,
	0x0f, 0xea, 0xa2, 0x8c, 0x43, 0x42, 0xeb, 0xa2, 0xb4, 0x85, 0x2e, 0x35, 0xaa, 0x94, 0x4f, 0xb1,
	0x30, 0x31, 0xb8, 0x42, 0x2d, 0xf2, 0xc2, 0x02, 0x76, 0xc0, 0xa2, 0x30, 0xa8, 0x78, 0x66, 0x84,
	0x2c, 0x74, 0xdc, 0xa5, 0x01, 0x3f, 0xdd, 0x29, 0x61, 0x2b, 0x78, 0x32, 0xdc, 0x61, 0xba, 0xf9,
	0xbe, 0x16, 0xcc, 0xae, 0x80, 0x55, 0xa2, 0x68, 0xc3, 0x95, 0x49, 0xed, 0x55, 0xc4, 0x07, 0x27,
	0xb5, 0x41, 0xf7, 0xb2, 0x9f, 0xb8, 0x93, 0x49, 0xaa, 0x93, 0x49, 0x6e, 0xab, 0x93, 0x19, 0x45,
	0x3e, 0xea, 0xc6, 0x06, 0x59, 0x98, 0x3d, 0x83, 0x9e, 0x71, 0x9b, 0x95, 0xfa, 0xa3, 0x39, 0xa4,
	0x2c, 0x47, 0xff, 0xb1, 0x79, 0xa3, 0x43, 0xb3, 0x6b, 0xf6, 0x9f, 0xc3, 0xa3, 0x7f, 0x15, 0xbb,
	0xbb, 0x6b, 0xe1, 0x1b, 0x76, 0xad, 0xb9, 0xbb, 0x6b, 0x7f, 0x35, 0xa0, 0x49, 0xad, 0xb3, 0x8f,
	0xe0, 0x51, 0x35, 0x4a, 0x2b, 0xb0, 0x2e, 0xf9, 0xe6, 0x84, 0x23, 0xef, 0xf8, 0xa9, 0xc2, 0xad,
	0xda, 0x15, 0x79, 0xbb, 0x75, 0x1e, 0x19, 0xe6, 0xec, 0x7c, 0xf3, 0x06, 0x34, 0xa8, 0x9d, 0x77,
	0xdf, 0xa8, 0xf3, 0xe6, 0x69, 0x48, 0x20, 0x20, 0x05, 0x83, 0xb7, 0x2a, 0x48, 0x3c, 0xf6, 0x14,
	0x02, 0xda, 0xa3, 0x26, 0xed, 0xd1, 0x3b, 0x7b, 0xc9, 0x69, 0x8d, 0x88, 0xc0, 0x8e, 0xa0, 0xfd,
	0xbb, 0x96, 0x45, 0x3a, 0xcf, 0xfd, 0x5e, 0xb6, 0xac, 0xf9, 0x63, 0xce, 0x9e, 0x53, 0xfd, 0x25,
	0x2a, 0x23, 0x50, 0xc7, 0x6d, 0x5a, 0x86, 0xe3, 0xbd, 0x3c, 0xc9, 0xf5, 0x86, 0xe1, 0x96, 0x60,
	0x27, 0x84, 0x9d, 0x43, 0xb0, 0x40, 0xc3, 0xfd, 0x43, 0xf1, 0x64, 0x3f, 0xf4, 0x15, 0x1a, 0xee,
	0x82, 0x88, 0xd6, 0xff, 0x0a, 0x1e, 0xee, 0x65, 0x7b, 0xdb, 0x94, 0x76, 0x5f, 0x84, 0xfe, 0x67,
	0x10, 0x6e, 0x32, 0xfe, 0x9f, 0xc0, 0xd3, 0x6f, 0xe1, 0x90, 0x0a, 0x1a, 0xa1, 0x2e, 0x65, 0xa1,
	0xe9, 0x15, 0xd6, 0xcb, 0x2c, 0x43, 0xad, 0x29, 0x41, 0x67, 0x54, 0x99, 0xec, 0x09, 0x74, 0xa8,
	0x85, 0xed, 0x40, 0xdb, 0x64, 0x0f, 0xf3, 0xb3, 0xdf, 0x00, 0xb6, 0x17, 0xca, 0xda, 0xd0, 0xb8,
	0xc3, 0x71, 0xf4, 0x80, 0x01, 0xb4, 0x5e, 0xc9, 0xb1, 0x98, 0x63, 0x54, 0xb3, 0xe0, 0x8b, 0xeb,
	0x61, 0x54, 0x67, 0x21, 0x34, 0xaf, 0x67, 0xb2, 0xc0, 0xa8, 0xc1, 0x7a, 0x00, 0x23, 0xe4, 0xf3,
	0xf4, 0x4e, 0xaa, 0x79, 0x1e, 0x05, 0xac, 0x0b, 0xed, 0x3b, 0x1c, 0xcf, 0xa4, 0xbc, 0x8f, 0x9a,
	0x96, 0xf7, 0xb3, 0x99, 0xa1, 0x8a, 0x5a, 0x67, 0x57, 0x10, 0x6e, 0x06, 0x67, 0xf1, 0x97, 0x2b,
	0x2c, 0x4c, 0xf4, 0x80, 0x1d, 0x40, 0xc7, 0x8b, 0xb6, 0x8e, 0x6a, 0x36, 0xfa, 0x0a, 0xb9, 0x59,
	0xf0, 0x32, 0xaa, 0xb3, 0x0e, 0x04, 0xdf, 0x49, 0xb5, 0x88, 0x1a, 0x16, 0xfe, 0x1e, 0x0b, 0x54,
	0x22, 0x8b, 0x82, 0xcb, 0x2f, 0xa1, 0x45, 0x99, 0x34, 0xfb, 0x18, 0x9a, 0x77, 0x4a, 0x18, 0x64,
	0x0f, 0xf7, 0x46, 0xd3, 0x3f, 0xda, 0x03, 0x2a, 0x69, 0xbe, 0x3e, 0xfb, 0x75, 0x30, 0x15, 0x66,
	0xb6, 0x1c, 0x27, 0x99, 0x5c, 0x5c, 0xd0, 0xc1, 0x3b, 0x9e, 0xfb, 0xf7, 0x3b, 0x9f, 0xca, 0x8b,
	0x2a, 0x72, 0xdc, 0x22, 0xe8, 0x93, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x88, 0x26, 0xcc, 0x89,
	0x38, 0x07, 0x00, 0x00,
}
