// Code generated by protoc-gen-go.
// source: impart.proto
// DO NOT EDIT!

/*
Package impart is a generated protocol buffer package.

It is generated from these files:
	impart.proto

It has these top-level messages:
	Source
	Entity
	Relationship
	Measurement
	Event
	Response
*/
package impart

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entity_State int32

const (
	Entity_pending  Entity_State = 0
	Entity_active   Entity_State = 1
	Entity_archived Entity_State = 2
	Entity_delete   Entity_State = 3
)

var Entity_State_name = map[int32]string{
	0: "pending",
	1: "active",
	2: "archived",
	3: "delete",
}
var Entity_State_value = map[string]int32{
	"pending":  0,
	"active":   1,
	"archived": 2,
	"delete":   3,
}

func (x Entity_State) String() string {
	return proto.EnumName(Entity_State_name, int32(x))
}
func (Entity_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Source struct {
	TrackerId  string                     `protobuf:"bytes,1,opt,name=tracker_id,json=trackerId" json:"tracker_id,omitempty"`
	Occurred   *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=occurred" json:"occurred,omitempty"`
	Attributes map[string]string          `protobuf:"bytes,3,rep,name=attributes" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Source) Reset()                    { *m = Source{} }
func (m *Source) String() string            { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()               {}
func (*Source) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Source) GetTrackerId() string {
	if m != nil {
		return m.TrackerId
	}
	return ""
}

func (m *Source) GetOccurred() *google_protobuf.Timestamp {
	if m != nil {
		return m.Occurred
	}
	return nil
}

func (m *Source) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type Entity struct {
	Id            string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name          string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description   string            `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	State         Entity_State      `protobuf:"varint,4,opt,name=state,enum=impart.Entity_State" json:"state,omitempty"`
	Status        float64           `protobuf:"fixed64,5,opt,name=status" json:"status,omitempty"`
	Schema        string            `protobuf:"bytes,6,opt,name=schema" json:"schema,omitempty"`
	SchemaVersion int32             `protobuf:"varint,7,opt,name=schema_version,json=schemaVersion" json:"schema_version,omitempty"`
	Attributes    map[string]string `protobuf:"bytes,8,rep,name=attributes" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels        map[string]string `protobuf:"bytes,9,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Source        *Source           `protobuf:"bytes,10,opt,name=source" json:"source,omitempty"`
}

func (m *Entity) Reset()                    { *m = Entity{} }
func (m *Entity) String() string            { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()               {}
func (*Entity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Entity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Entity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Entity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Entity) GetState() Entity_State {
	if m != nil {
		return m.State
	}
	return Entity_pending
}

func (m *Entity) GetStatus() float64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Entity) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *Entity) GetSchemaVersion() int32 {
	if m != nil {
		return m.SchemaVersion
	}
	return 0
}

func (m *Entity) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Entity) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Entity) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type Relationship struct {
	EntityId         string            `protobuf:"bytes,1,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	RelatedEntityId  string            `protobuf:"bytes,2,opt,name=related_entity_id,json=relatedEntityId" json:"related_entity_id,omitempty"`
	RelationshipType string            `protobuf:"bytes,3,opt,name=relationship_type,json=relationshipType" json:"relationship_type,omitempty"`
	Attributes       map[string]string `protobuf:"bytes,4,rep,name=attributes" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Source           *Source           `protobuf:"bytes,5,opt,name=source" json:"source,omitempty"`
}

func (m *Relationship) Reset()                    { *m = Relationship{} }
func (m *Relationship) String() string            { return proto.CompactTextString(m) }
func (*Relationship) ProtoMessage()               {}
func (*Relationship) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Relationship) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *Relationship) GetRelatedEntityId() string {
	if m != nil {
		return m.RelatedEntityId
	}
	return ""
}

func (m *Relationship) GetRelationshipType() string {
	if m != nil {
		return m.RelationshipType
	}
	return ""
}

func (m *Relationship) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Relationship) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type Measurement struct {
	EntityId string  `protobuf:"bytes,1,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	Property string  `protobuf:"bytes,2,opt,name=property" json:"property,omitempty"`
	Value    int64   `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
	Source   *Source `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
}

func (m *Measurement) Reset()                    { *m = Measurement{} }
func (m *Measurement) String() string            { return proto.CompactTextString(m) }
func (*Measurement) ProtoMessage()               {}
func (*Measurement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Measurement) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *Measurement) GetProperty() string {
	if m != nil {
		return m.Property
	}
	return ""
}

func (m *Measurement) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Measurement) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type Event struct {
	EventId          string             `protobuf:"bytes,1,opt,name=event_id,json=eventId" json:"event_id,omitempty"`
	EntityId         string             `protobuf:"bytes,2,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	Source           *Source            `protobuf:"bytes,3,opt,name=source" json:"source,omitempty"`
	Schema           string             `protobuf:"bytes,4,opt,name=schema" json:"schema,omitempty"`
	SchemaVersion    int32              `protobuf:"varint,5,opt,name=schema_version,json=schemaVersion" json:"schema_version,omitempty"`
	Attributes       map[string]string  `protobuf:"bytes,6,rep,name=attributes" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	JsonLd           string             `protobuf:"bytes,7,opt,name=jsonLd" json:"jsonLd,omitempty"`
	RelatedEntityIds []string           `protobuf:"bytes,8,rep,name=related_entity_ids,json=relatedEntityIds" json:"related_entity_ids,omitempty"`
	Extensions       []*Event_Extension `protobuf:"bytes,9,rep,name=extensions" json:"extensions,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Event) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *Event) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *Event) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Event) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *Event) GetSchemaVersion() int32 {
	if m != nil {
		return m.SchemaVersion
	}
	return 0
}

func (m *Event) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Event) GetJsonLd() string {
	if m != nil {
		return m.JsonLd
	}
	return ""
}

func (m *Event) GetRelatedEntityIds() []string {
	if m != nil {
		return m.RelatedEntityIds
	}
	return nil
}

func (m *Event) GetExtensions() []*Event_Extension {
	if m != nil {
		return m.Extensions
	}
	return nil
}

type Event_Extension struct {
	Schema        string            `protobuf:"bytes,1,opt,name=schema" json:"schema,omitempty"`
	SchemaVersion int32             `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion" json:"schema_version,omitempty"`
	Attributes    map[string]string `protobuf:"bytes,3,rep,name=attributes" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Event_Extension) Reset()                    { *m = Event_Extension{} }
func (m *Event_Extension) String() string            { return proto.CompactTextString(m) }
func (*Event_Extension) ProtoMessage()               {}
func (*Event_Extension) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *Event_Extension) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *Event_Extension) GetSchemaVersion() int32 {
	if m != nil {
		return m.SchemaVersion
	}
	return 0
}

func (m *Event_Extension) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type Response struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Source)(nil), "impart.Source")
	proto.RegisterType((*Entity)(nil), "impart.Entity")
	proto.RegisterType((*Relationship)(nil), "impart.Relationship")
	proto.RegisterType((*Measurement)(nil), "impart.Measurement")
	proto.RegisterType((*Event)(nil), "impart.Event")
	proto.RegisterType((*Event_Extension)(nil), "impart.Event.Extension")
	proto.RegisterType((*Response)(nil), "impart.Response")
	proto.RegisterEnum("impart.Entity_State", Entity_State_name, Entity_State_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Impart service

type ImpartClient interface {
	MutateEntity(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*Response, error)
	Relate(ctx context.Context, in *Relationship, opts ...grpc.CallOption) (*Response, error)
	Instrument(ctx context.Context, in *Measurement, opts ...grpc.CallOption) (*Response, error)
	Metric(ctx context.Context, in *Measurement, opts ...grpc.CallOption) (*Response, error)
	CreateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Response, error)
}

type impartClient struct {
	cc *grpc.ClientConn
}

func NewImpartClient(cc *grpc.ClientConn) ImpartClient {
	return &impartClient{cc}
}

func (c *impartClient) MutateEntity(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/impart.Impart/MutateEntity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impartClient) Relate(ctx context.Context, in *Relationship, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/impart.Impart/Relate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impartClient) Instrument(ctx context.Context, in *Measurement, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/impart.Impart/Instrument", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impartClient) Metric(ctx context.Context, in *Measurement, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/impart.Impart/Metric", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *impartClient) CreateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/impart.Impart/CreateEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Impart service

type ImpartServer interface {
	MutateEntity(context.Context, *Entity) (*Response, error)
	Relate(context.Context, *Relationship) (*Response, error)
	Instrument(context.Context, *Measurement) (*Response, error)
	Metric(context.Context, *Measurement) (*Response, error)
	CreateEvent(context.Context, *Event) (*Response, error)
}

func RegisterImpartServer(s *grpc.Server, srv ImpartServer) {
	s.RegisterService(&_Impart_serviceDesc, srv)
}

func _Impart_MutateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpartServer).MutateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impart.Impart/MutateEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpartServer).MutateEntity(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Impart_Relate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Relationship)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpartServer).Relate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impart.Impart/Relate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpartServer).Relate(ctx, req.(*Relationship))
	}
	return interceptor(ctx, in, info, handler)
}

func _Impart_Instrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Measurement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpartServer).Instrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impart.Impart/Instrument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpartServer).Instrument(ctx, req.(*Measurement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Impart_Metric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Measurement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpartServer).Metric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impart.Impart/Metric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpartServer).Metric(ctx, req.(*Measurement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Impart_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImpartServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/impart.Impart/CreateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImpartServer).CreateEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

var _Impart_serviceDesc = grpc.ServiceDesc{
	ServiceName: "impart.Impart",
	HandlerType: (*ImpartServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MutateEntity",
			Handler:    _Impart_MutateEntity_Handler,
		},
		{
			MethodName: "Relate",
			Handler:    _Impart_Relate_Handler,
		},
		{
			MethodName: "Instrument",
			Handler:    _Impart_Instrument_Handler,
		},
		{
			MethodName: "Metric",
			Handler:    _Impart_Metric_Handler,
		},
		{
			MethodName: "CreateEvent",
			Handler:    _Impart_CreateEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "impart.proto",
}

func init() { proto.RegisterFile("impart.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 816 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0xc6, 0x4e, 0xec, 0x38, 0x27, 0x69, 0x1a, 0x86, 0x55, 0x31, 0x46, 0x05, 0x2b, 0x2a, 0x10,
	0x15, 0x70, 0xaa, 0x54, 0xe2, 0xa7, 0x52, 0x91, 0xf8, 0x89, 0x50, 0xa4, 0xee, 0x8d, 0x5b, 0x71,
	0xc1, 0x4d, 0xe4, 0xd8, 0x87, 0xc4, 0x6c, 0x62, 0x5b, 0x33, 0xe3, 0xa8, 0xb9, 0x45, 0xbc, 0x09,
	0x4f, 0xc0, 0xab, 0xf0, 0x00, 0x3c, 0x07, 0x97, 0xc8, 0x33, 0xe3, 0xd8, 0xce, 0x86, 0x2c, 0xd5,
	0x6a, 0xef, 0xe6, 0xfc, 0xcd, 0xf9, 0xe6, 0x7c, 0xf3, 0x8d, 0x0d, 0xfd, 0x78, 0x9b, 0x05, 0x94,
	0x7b, 0x19, 0x4d, 0x79, 0x4a, 0x4c, 0x69, 0x39, 0x1f, 0xae, 0xd2, 0x74, 0xb5, 0xc1, 0x89, 0xf0,
	0x2e, 0xf3, 0x5f, 0x26, 0x3c, 0xde, 0x22, 0xe3, 0xc1, 0x36, 0x93, 0x89, 0xa3, 0xbf, 0x35, 0x30,
	0x5f, 0xa6, 0x39, 0x0d, 0x91, 0x3c, 0x04, 0xe0, 0x34, 0x08, 0xaf, 0x90, 0x2e, 0xe2, 0xc8, 0xd6,
	0x5c, 0x6d, 0xdc, 0xf5, 0xbb, 0xca, 0x33, 0x8f, 0xc8, 0x17, 0x60, 0xa5, 0x61, 0x98, 0x53, 0x8a,
	0x91, 0xad, 0xbb, 0xda, 0xb8, 0x37, 0x75, 0x3c, 0xb9, 0xbb, 0x57, 0xee, 0xee, 0xbd, 0x2a, 0x77,
	0xf7, 0x0f, 0xb9, 0xe4, 0x1b, 0x80, 0x80, 0x73, 0x1a, 0x2f, 0x73, 0x8e, 0xcc, 0x6e, 0xb9, 0xad,
	0x71, 0x6f, 0xfa, 0x81, 0xa7, 0xd0, 0xca, 0xd6, 0xde, 0xb7, 0x87, 0x84, 0x59, 0xc2, 0xe9, 0xde,
	0xaf, 0x55, 0x38, 0xcf, 0xe1, 0xfe, 0x51, 0x98, 0x0c, 0xa1, 0x75, 0x85, 0x7b, 0x05, 0xb1, 0x58,
	0x92, 0x0b, 0x30, 0x76, 0xc1, 0x26, 0x47, 0x81, 0xac, 0xeb, 0x4b, 0xe3, 0x99, 0xfe, 0x95, 0x36,
	0xfa, 0xa3, 0x0d, 0xe6, 0x2c, 0xe1, 0x31, 0xdf, 0x93, 0x01, 0xe8, 0x87, 0x83, 0xe9, 0x71, 0x44,
	0x08, 0xb4, 0x93, 0x60, 0x5b, 0xd6, 0x88, 0x35, 0x71, 0xa1, 0x17, 0x21, 0x0b, 0x69, 0x9c, 0xf1,
	0x38, 0x4d, 0xec, 0x96, 0x08, 0xd5, 0x5d, 0xe4, 0x31, 0x18, 0x8c, 0x07, 0x1c, 0xed, 0xb6, 0xab,
	0x8d, 0x07, 0xd3, 0x8b, 0xf2, 0x28, 0xb2, 0x89, 0xf7, 0xb2, 0x88, 0xf9, 0x32, 0x85, 0x3c, 0x00,
	0xb3, 0x58, 0xe4, 0xcc, 0x36, 0x5c, 0x6d, 0xac, 0xf9, 0xca, 0x12, 0xfe, 0x70, 0x8d, 0xdb, 0xc0,
	0x36, 0x45, 0x03, 0x65, 0x91, 0x8f, 0x60, 0x20, 0x57, 0x8b, 0x1d, 0x52, 0x56, 0x00, 0xe8, 0xb8,
	0xda, 0xd8, 0xf0, 0xef, 0x49, 0xef, 0x4f, 0xd2, 0x79, 0x34, 0x52, 0xab, 0x39, 0x52, 0x85, 0xe3,
	0xcc, 0x48, 0xc9, 0x14, 0xcc, 0x4d, 0xb0, 0xc4, 0x0d, 0xb3, 0xbb, 0xa2, 0xd6, 0x39, 0xaa, 0x7d,
	0x21, 0x82, 0xb2, 0x4e, 0x65, 0x92, 0x8f, 0xc1, 0x64, 0x82, 0x2c, 0x1b, 0x04, 0xf9, 0x83, 0x26,
	0x85, 0xbe, 0x8a, 0xde, 0x92, 0x2e, 0xe7, 0x6b, 0xe8, 0xd5, 0xba, 0xbf, 0x11, 0xd3, 0xcf, 0xc0,
	0x10, 0xc3, 0x27, 0x3d, 0xe8, 0x64, 0x98, 0x44, 0x71, 0xb2, 0x1a, 0xbe, 0x45, 0x00, 0xcc, 0x20,
	0xe4, 0xf1, 0x0e, 0x87, 0x1a, 0xe9, 0x83, 0x15, 0xd0, 0x70, 0x1d, 0xef, 0x30, 0x1a, 0xea, 0x45,
	0x24, 0xc2, 0x0d, 0x72, 0x1c, 0xb6, 0x46, 0x7f, 0xea, 0xd0, 0xf7, 0x71, 0x13, 0x14, 0x0c, 0xb3,
	0x75, 0x9c, 0x91, 0xf7, 0xa1, 0x8b, 0x62, 0x18, 0x95, 0x16, 0x2c, 0xe9, 0x98, 0x47, 0xe4, 0x31,
	0xbc, 0x4d, 0x8b, 0x64, 0x8c, 0x16, 0x55, 0x92, 0xc4, 0x73, 0x5f, 0x05, 0x66, 0x65, 0xee, 0xa7,
	0x2a, 0x57, 0x6d, 0xbc, 0xe0, 0xfb, 0x0c, 0xd5, 0xb5, 0x1a, 0xd6, 0x03, 0xaf, 0xf6, 0x19, 0x92,
	0x1f, 0x1a, 0xc4, 0xb6, 0x05, 0x39, 0x8f, 0xca, 0x41, 0xd7, 0xf1, 0x9d, 0xa5, 0xb7, 0xa2, 0xca,
	0xb8, 0x43, 0xaa, 0x46, 0xbf, 0x6b, 0xd0, 0xbb, 0xc4, 0x80, 0xe5, 0x14, 0xb7, 0x98, 0xf0, 0xf3,
	0x23, 0x73, 0xc0, 0xca, 0x68, 0x9a, 0x21, 0xe5, 0x7b, 0xb5, 0xd3, 0xc1, 0xae, 0x5a, 0x14, 0x63,
	0x69, 0xa9, 0x16, 0xb5, 0x53, 0xb4, 0xcf, 0x9d, 0x62, 0xf4, 0x4f, 0x1b, 0x8c, 0xd9, 0xae, 0x00,
	0xf0, 0x1e, 0x58, 0x58, 0x2c, 0xaa, 0xfe, 0x1d, 0x61, 0xcf, 0xa3, 0x26, 0x36, 0xfd, 0x08, 0x5b,
	0xd5, 0xa9, 0x75, 0xae, 0x53, 0x4d, 0xb5, 0xed, 0x1b, 0x54, 0x6b, 0x9c, 0x52, 0xed, 0xf3, 0x06,
	0xb9, 0xa6, 0x20, 0xf7, 0xe1, 0x41, 0x79, 0x05, 0xd0, 0xb3, 0xac, 0x3e, 0x00, 0xf3, 0x57, 0x96,
	0x26, 0x2f, 0x22, 0xf1, 0x26, 0x74, 0x7d, 0x65, 0x91, 0xcf, 0x80, 0x5c, 0xbb, 0x8c, 0xf2, 0x51,
	0x28, 0x6f, 0x58, 0x75, 0x1b, 0x19, 0xf9, 0x12, 0x00, 0x5f, 0x73, 0x4c, 0x0a, 0x44, 0xa5, 0xfc,
	0xdf, 0x6d, 0x82, 0x98, 0x95, 0x71, 0xbf, 0x96, 0xea, 0xfc, 0xa5, 0x41, 0xf7, 0x10, 0xa9, 0x8d,
	0x42, 0xbb, 0x61, 0x14, 0xfa, 0xa9, 0x51, 0xfc, 0x78, 0xe2, 0x9b, 0xf0, 0xc9, 0x7f, 0xa0, 0xb8,
	0xc3, 0x8f, 0xc3, 0x6d, 0x15, 0xf0, 0x08, 0x2c, 0x1f, 0x59, 0x96, 0x26, 0x0c, 0x89, 0x0d, 0x1d,
	0x96, 0x87, 0x21, 0x32, 0x26, 0x6a, 0x2d, 0xbf, 0x34, 0xa7, 0xbf, 0xe9, 0x60, 0xce, 0xc5, 0xd1,
	0xc8, 0x13, 0xe8, 0x5f, 0xe6, 0xc5, 0x1b, 0x55, 0x7e, 0x91, 0x9a, 0x0f, 0xaf, 0x33, 0xac, 0xb4,
	0xae, 0xb6, 0x7d, 0x02, 0xa6, 0xd0, 0x3d, 0x92, 0x8b, 0x53, 0xef, 0xc0, 0x89, 0x8a, 0xa7, 0x00,
	0xf3, 0x84, 0x71, 0x9a, 0x0b, 0x51, 0xbe, 0x53, 0xc6, 0x6b, 0x4a, 0x3d, 0x51, 0x34, 0x01, 0xf3,
	0x12, 0x39, 0x8d, 0xc3, 0xff, 0x5b, 0xe0, 0x41, 0xef, 0x7b, 0x8a, 0xc5, 0x49, 0x84, 0xf4, 0xee,
	0x35, 0xc8, 0xbb, 0x9e, 0xff, 0xdd, 0xe8, 0x67, 0x77, 0x15, 0xf3, 0x75, 0xbe, 0xf4, 0xc2, 0x74,
	0x3b, 0xb9, 0xca, 0x97, 0xf8, 0x5a, 0xfe, 0x94, 0x7c, 0xbe, 0x4a, 0x27, 0x32, 0x79, 0x69, 0x0a,
	0xc7, 0xd3, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xae, 0xf9, 0xbf, 0x25, 0xcb, 0x08, 0x00, 0x00,
}
