// Code generated by protoc-gen-go. DO NOT EDIT.
// source: socket.proto

/*
Package socket is a generated protocol buffer package.

It is generated from these files:
	socket.proto

It has these top-level messages:
	SocketMessage
	SubscribeMessage
	PublishResponse
*/
package socket

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SocketMessage struct {
	AppId   string `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	Channel string `protobuf:"bytes,2,opt,name=channel" json:"channel,omitempty"`
	Action  string `protobuf:"bytes,3,opt,name=action" json:"action,omitempty"`
	Payload string `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
}

func (m *SocketMessage) Reset()                    { *m = SocketMessage{} }
func (m *SocketMessage) String() string            { return proto.CompactTextString(m) }
func (*SocketMessage) ProtoMessage()               {}
func (*SocketMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SocketMessage) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SocketMessage) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *SocketMessage) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *SocketMessage) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type SubscribeMessage struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	AppId     string `protobuf:"bytes,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	Channel   string `protobuf:"bytes,3,opt,name=channel" json:"channel,omitempty"`
}

func (m *SubscribeMessage) Reset()                    { *m = SubscribeMessage{} }
func (m *SubscribeMessage) String() string            { return proto.CompactTextString(m) }
func (*SubscribeMessage) ProtoMessage()               {}
func (*SubscribeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SubscribeMessage) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *SubscribeMessage) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SubscribeMessage) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type PublishResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *PublishResponse) Reset()                    { *m = PublishResponse{} }
func (m *PublishResponse) String() string            { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()               {}
func (*PublishResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PublishResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PublishResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*SocketMessage)(nil), "socket.SocketMessage")
	proto.RegisterType((*SubscribeMessage)(nil), "socket.SubscribeMessage")
	proto.RegisterType((*PublishResponse)(nil), "socket.PublishResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Socket service

type SocketClient interface {
	Publish(ctx context.Context, in *SocketMessage, opts ...grpc.CallOption) (*PublishResponse, error)
	Subscribe(ctx context.Context, in *SubscribeMessage, opts ...grpc.CallOption) (*PublishResponse, error)
	UnSubscribe(ctx context.Context, in *SubscribeMessage, opts ...grpc.CallOption) (*PublishResponse, error)
}

type socketClient struct {
	cc *grpc.ClientConn
}

func NewSocketClient(cc *grpc.ClientConn) SocketClient {
	return &socketClient{cc}
}

func (c *socketClient) Publish(ctx context.Context, in *SocketMessage, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := grpc.Invoke(ctx, "/socket.Socket/Publish", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketClient) Subscribe(ctx context.Context, in *SubscribeMessage, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := grpc.Invoke(ctx, "/socket.Socket/Subscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketClient) UnSubscribe(ctx context.Context, in *SubscribeMessage, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := grpc.Invoke(ctx, "/socket.Socket/UnSubscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Socket service

type SocketServer interface {
	Publish(context.Context, *SocketMessage) (*PublishResponse, error)
	Subscribe(context.Context, *SubscribeMessage) (*PublishResponse, error)
	UnSubscribe(context.Context, *SubscribeMessage) (*PublishResponse, error)
}

func RegisterSocketServer(s *grpc.Server, srv SocketServer) {
	s.RegisterService(&_Socket_serviceDesc, srv)
}

func _Socket_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SocketMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socket.Socket/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketServer).Publish(ctx, req.(*SocketMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Socket_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socket.Socket/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketServer).Subscribe(ctx, req.(*SubscribeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Socket_UnSubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketServer).UnSubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socket.Socket/UnSubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketServer).UnSubscribe(ctx, req.(*SubscribeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Socket_serviceDesc = grpc.ServiceDesc{
	ServiceName: "socket.Socket",
	HandlerType: (*SocketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _Socket_Publish_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _Socket_Subscribe_Handler,
		},
		{
			MethodName: "UnSubscribe",
			Handler:    _Socket_UnSubscribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "socket.proto",
}

func init() { proto.RegisterFile("socket.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0xd9, 0xe6, 0x3a, 0xf7, 0xaa, 0x28, 0xc1, 0x69, 0x10, 0x84, 0xd1, 0x93, 0x17, 0x57,
	0xd0, 0x93, 0x17, 0x51, 0x6f, 0x3b, 0x08, 0xd2, 0xe1, 0xc5, 0x8b, 0x24, 0xe9, 0x4b, 0x1b, 0x56,
	0x93, 0x90, 0xb7, 0x05, 0xfd, 0x80, 0x7e, 0x2f, 0x59, 0xda, 0x4e, 0x37, 0xd8, 0xc9, 0x5b, 0x7e,
	0x4f, 0xf2, 0x3c, 0xef, 0x1f, 0x02, 0x87, 0x64, 0xd5, 0x12, 0xab, 0x99, 0xf3, 0xb6, 0xb2, 0x2c,
	0x6a, 0x28, 0xf6, 0x70, 0xb4, 0x08, 0xa7, 0x67, 0x24, 0x12, 0x39, 0xb2, 0x09, 0x44, 0xc2, 0xb9,
	0x77, 0x9d, 0xf1, 0xde, 0xb4, 0x77, 0x35, 0x4e, 0x87, 0xc2, 0xb9, 0x79, 0xc6, 0x38, 0x8c, 0x54,
	0x21, 0x8c, 0xc1, 0x92, 0xf7, 0x83, 0xde, 0x21, 0x3b, 0x83, 0x48, 0xa8, 0x4a, 0x5b, 0xc3, 0x07,
	0xe1, 0xa2, 0xa5, 0x95, 0xc3, 0x89, 0xaf, 0xd2, 0x8a, 0x8c, 0xef, 0x35, 0x8e, 0x16, 0x63, 0x09,
	0x27, 0x8b, 0x5a, 0x92, 0xf2, 0x5a, 0x62, 0x57, 0xf6, 0x12, 0x80, 0x90, 0x48, 0x5b, 0xf3, 0x5b,
	0x7a, 0xdc, 0x2a, 0xf3, 0xec, 0x4f, 0x57, 0xfd, 0x1d, 0x5d, 0x0d, 0x36, 0xba, 0x8a, 0x1f, 0xe1,
	0xf8, 0xa5, 0x96, 0xa5, 0xa6, 0x22, 0x45, 0x72, 0xd6, 0x10, 0xae, 0x1e, 0x53, 0xad, 0x14, 0x12,
	0x85, 0xfc, 0xfd, 0xb4, 0x43, 0x76, 0x0a, 0x43, 0xf4, 0xde, 0xfa, 0x2e, 0x3c, 0xc0, 0xcd, 0x77,
	0x0f, 0xa2, 0x66, 0x37, 0xec, 0x0e, 0x46, 0x6d, 0x1a, 0x9b, 0xcc, 0xda, 0x3d, 0x6e, 0xac, 0xed,
	0xe2, 0xbc, 0x93, 0xb7, 0xab, 0xde, 0xc3, 0x78, 0x3d, 0x2c, 0xe3, 0x6b, 0xf3, 0xd6, 0xfc, 0xbb,
	0xfd, 0x0f, 0x70, 0xf0, 0x6a, 0xfe, 0x93, 0xf0, 0x14, 0xbf, 0x4d, 0x73, 0x5d, 0x15, 0xb5, 0x9c,
	0x29, 0xfb, 0x91, 0x2c, 0x6b, 0x89, 0x9f, 0x49, 0xf8, 0x04, 0xd7, 0xb9, 0x4d, 0x1a, 0x8f, 0x8c,
	0x82, 0x70, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0x59, 0x72, 0x7e, 0x8e, 0x25, 0x02, 0x00, 0x00,
}
