// Code generated by protoc-gen-go.
// source: vendors.proto
// DO NOT EDIT!

/*
Package vendors is a generated protocol buffer package.

Storage of applications

It is generated from these files:
	vendors.proto

It has these top-level messages:
	RetrieveRequest
	RegisterRequest
	RegisterResponse
	Response
	UpdateRequest
	ListRequest
	UpdateResponse
	VendorsResponse
*/
package vendors

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RetrieveRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *RetrieveRequest) Reset()                    { *m = RetrieveRequest{} }
func (m *RetrieveRequest) String() string            { return proto.CompactTextString(m) }
func (*RetrieveRequest) ProtoMessage()               {}
func (*RetrieveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RetrieveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RegisterRequest struct {
	ProjectId   string `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	Id          string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *RegisterRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type RegisterResponse struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	EntityCode string `protobuf:"bytes,2,opt,name=entity_code,json=entityCode" json:"entity_code,omitempty"`
	Secret     string `protobuf:"bytes,3,opt,name=secret" json:"secret,omitempty"`
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RegisterResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegisterResponse) GetEntityCode() string {
	if m != nil {
		return m.EntityCode
	}
	return ""
}

func (m *RegisterResponse) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type Response struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	EntityCode  string `protobuf:"bytes,4,opt,name=entity_code,json=entityCode" json:"entity_code,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Response) GetEntityCode() string {
	if m != nil {
		return m.EntityCode
	}
	return ""
}

type UpdateRequest struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ListRequest struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type UpdateResponse struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Updated bool   `protobuf:"varint,2,opt,name=updated" json:"updated,omitempty"`
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateResponse) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

type VendorsResponse struct {
	Vendors []*Response `protobuf:"bytes,1,rep,name=vendors" json:"vendors,omitempty"`
}

func (m *VendorsResponse) Reset()                    { *m = VendorsResponse{} }
func (m *VendorsResponse) String() string            { return proto.CompactTextString(m) }
func (*VendorsResponse) ProtoMessage()               {}
func (*VendorsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *VendorsResponse) GetVendors() []*Response {
	if m != nil {
		return m.Vendors
	}
	return nil
}

func init() {
	proto.RegisterType((*RetrieveRequest)(nil), "vendors.RetrieveRequest")
	proto.RegisterType((*RegisterRequest)(nil), "vendors.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "vendors.RegisterResponse")
	proto.RegisterType((*Response)(nil), "vendors.Response")
	proto.RegisterType((*UpdateRequest)(nil), "vendors.UpdateRequest")
	proto.RegisterType((*ListRequest)(nil), "vendors.ListRequest")
	proto.RegisterType((*UpdateResponse)(nil), "vendors.UpdateResponse")
	proto.RegisterType((*VendorsResponse)(nil), "vendors.VendorsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Vendors service

type VendorsClient interface {
	Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*VendorsResponse, error)
}

type vendorsClient struct {
	cc *grpc.ClientConn
}

func NewVendorsClient(cc *grpc.ClientConn) VendorsClient {
	return &vendorsClient{cc}
}

func (c *vendorsClient) Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/vendors.Vendors/Retrieve", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorsClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := grpc.Invoke(ctx, "/vendors.Vendors/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorsClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := grpc.Invoke(ctx, "/vendors.Vendors/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorsClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*VendorsResponse, error) {
	out := new(VendorsResponse)
	err := grpc.Invoke(ctx, "/vendors.Vendors/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Vendors service

type VendorsServer interface {
	Retrieve(context.Context, *RetrieveRequest) (*Response, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	List(context.Context, *ListRequest) (*VendorsResponse, error)
}

func RegisterVendorsServer(s *grpc.Server, srv VendorsServer) {
	s.RegisterService(&_Vendors_serviceDesc, srv)
}

func _Vendors_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorsServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vendors.Vendors/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorsServer).Retrieve(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vendors_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vendors.Vendors/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorsServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vendors_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorsServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vendors.Vendors/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorsServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vendors_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vendors.Vendors/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorsServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Vendors_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vendors.Vendors",
	HandlerType: (*VendorsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Retrieve",
			Handler:    _Vendors_Retrieve_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Vendors_Update_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Vendors_Register_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Vendors_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vendors.proto",
}

func init() { proto.RegisterFile("vendors.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0x45, 0xb2, 0xf0, 0xc7, 0x08, 0xdb, 0xed, 0x52, 0x5c, 0x55, 0x50, 0x6a, 0x6f, 0x2f, 0x86,
	0xb6, 0x36, 0xb8, 0xd0, 0xd2, 0x1e, 0x5a, 0x68, 0x4f, 0x85, 0x9e, 0x04, 0xce, 0x21, 0x39, 0x18,
	0x5b, 0x3b, 0x38, 0x9b, 0x60, 0xad, 0xac, 0x5d, 0x99, 0xe4, 0x8f, 0xe7, 0x1c, 0x24, 0xed, 0xca,
	0x96, 0x1c, 0x41, 0xc8, 0x4d, 0x3b, 0xf3, 0xe6, 0xcd, 0xdb, 0xb7, 0x4f, 0xd0, 0x3f, 0x60, 0xc4,
	0x44, 0x22, 0x67, 0x71, 0x22, 0x94, 0x20, 0x1d, 0x7d, 0xa4, 0x13, 0x18, 0x06, 0xa8, 0x12, 0x8e,
	0x07, 0x0c, 0x70, 0x9f, 0xa2, 0x54, 0x64, 0x00, 0x36, 0x67, 0x9e, 0x35, 0xb6, 0xa6, 0xbd, 0xc0,
	0xe6, 0x8c, 0x1e, 0x32, 0xc8, 0x96, 0x4b, 0x85, 0x89, 0x81, 0xbc, 0x07, 0x88, 0x13, 0x71, 0x83,
	0xa1, 0x5a, 0x95, 0xd0, 0x9e, 0xae, 0xfc, 0x63, 0x9a, 0xc1, 0x36, 0x0c, 0x84, 0x80, 0x13, 0xad,
	0x77, 0xe8, 0xb5, 0xf2, 0x4a, 0xfe, 0x4d, 0xc6, 0xe0, 0x32, 0x94, 0x61, 0xc2, 0x63, 0xc5, 0x45,
	0xe4, 0x39, 0x79, 0xeb, 0xb4, 0x44, 0xaf, 0xe0, 0xd5, 0x71, 0xaf, 0x8c, 0x45, 0x24, 0xb1, 0xae,
	0x8d, 0x7c, 0x00, 0x17, 0x23, 0xc5, 0xd5, 0xfd, 0x2a, 0x14, 0x0c, 0xf5, 0x4a, 0x28, 0x4a, 0x7f,
	0x05, 0x43, 0x32, 0x82, 0xb6, 0xc4, 0x30, 0x41, 0xa5, 0x97, 0xeb, 0x13, 0xdd, 0x43, 0xb7, 0x91,
	0xd4, 0xc8, 0xb5, 0x9b, 0xe5, 0xb6, 0xce, 0xe4, 0xd6, 0xa5, 0x38, 0x75, 0x29, 0x74, 0x09, 0xfd,
	0x65, 0xcc, 0xd6, 0xaa, 0xc9, 0xe8, 0x97, 0xed, 0xa5, 0x9f, 0xc1, 0xfd, 0xcf, 0xa5, 0x7a, 0xde,
	0xd3, 0xd0, 0x9f, 0x30, 0x30, 0x22, 0x1a, 0x6e, 0xef, 0x41, 0x27, 0xcd, 0x11, 0xc5, 0x0b, 0x76,
	0x03, 0x73, 0xa4, 0xbf, 0x60, 0x78, 0x51, 0xc4, 0xa6, 0x1c, 0xfe, 0x04, 0x26, 0x49, 0x9e, 0x35,
	0x6e, 0x4d, 0xdd, 0xc5, 0xeb, 0x99, 0x09, 0x9a, 0xc1, 0x04, 0x06, 0xb1, 0x78, 0xb0, 0xa0, 0xa3,
	0x09, 0xc8, 0xf7, 0xcc, 0xff, 0x22, 0x77, 0xc4, 0x3b, 0x99, 0xa9, 0x44, 0xd1, 0x3f, 0x67, 0x23,
	0x3f, 0xa0, 0x5d, 0x5c, 0x80, 0x8c, 0xca, 0x66, 0xc5, 0x56, 0xff, 0xed, 0x59, 0x5d, 0x8f, 0xfe,
	0xce, 0x76, 0x16, 0x81, 0xaa, 0xec, 0xac, 0x64, 0xdb, 0x7f, 0xf7, 0x44, 0x47, 0x13, 0x7c, 0x03,
	0x27, 0xb3, 0x9a, 0xbc, 0x29, 0x21, 0x27, 0xce, 0xfb, 0x47, 0xca, 0x9a, 0x4b, 0x7f, 0x3e, 0x5e,
	0x4e, 0xb6, 0x5c, 0x5d, 0xa7, 0x9b, 0x59, 0x28, 0x76, 0xf3, 0xdb, 0x74, 0x83, 0x77, 0xf3, 0xfc,
	0x3f, 0xfc, 0xb2, 0x15, 0x73, 0x3d, 0xb4, 0x69, 0xe7, 0x95, 0xaf, 0x8f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x69, 0x1d, 0xf0, 0xaa, 0xaa, 0x03, 0x00, 0x00,
}
